import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Legal Disclaimer — PactTailor',
  description: 'PactTailor generates template documents, not legal advice. Read the full disclaimer before using our service.',
  openGraph: { url: 'https://pacttailor.com/legal/disclaimer' },
};

export default function DisclaimerPage() {
  const updated = 'April 12, 2026';
  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white border-b border-gray-200">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <Link href="/" className="font-bold text-indigo-700">PactTailor</Link>
          <Link href="/legal/terms" className="text-sm text-gray-500 hover:text-gray-700">Terms</Link>
        </div>
      </nav>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-12">
        <div className="bg-red-50 border border-red-200 rounded-xl p-5 mb-8">
          <p className="font-bold text-red-800 text-lg">⚠️ PactTailor is NOT a law firm and does NOT provide legal advice.</p>
          <p className="text-red-700 text-sm mt-2">
            The templates, documents, and outputs generated by PactTailor are provided for informational and general reference purposes only. They do not constitute, and should not be relied upon as, legal advice from a licensed attorney.
          </p>
        </div>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Legal Disclaimer</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: {updated}</p>

        <div className="prose prose-gray max-w-none space-y-6 text-sm text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">1. No Attorney-Client Relationship</h2>
            <p>Use of PactTailor does not create an attorney-client relationship between you and PactTailor, its operators, affiliates, or any third party. PactTailor is a software tool, not a legal service. No communication through PactTailor constitutes legal advice.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">2. Templates Are Not Legal Advice</h2>
            <p>The contract templates, clause libraries, and generated documents provided by PactTailor are <strong>starting points and general-purpose examples only</strong>. They are not tailored to your specific legal situation, jurisdiction, industry, or facts. PactTailor makes no representation that any template is legally sufficient, enforceable, or appropriate for your particular use case.</p>
            <p className="mt-2">You should always consult a licensed attorney in your jurisdiction before relying on any document generated by PactTailor for significant legal, financial, or business decisions.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">3. Jurisdiction Limitations</h2>
            <p>While PactTailor attempts to tailor templates to selected jurisdictions (US, EU, UK, AU, CA), the legal requirements and enforceability standards vary significantly by state, country, and local law. PactTailor does not warrant that any template complies with the laws of any specific jurisdiction. Jurisdiction filters are <strong>guidance tools only</strong>, not legal determinations.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">4. No Warranty</h2>
            <p>PactTailor provides all templates and services "as is" and "as available" without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, accuracy, completeness, or non-infringement. PactTailor does not warrant that documents generated through the service are free from errors or are legally valid.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">5. Limitation of Liability</h2>
            <p>To the maximum extent permitted by applicable law, PactTailor and its operators shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising from your use of, or reliance on, any template or document generated by PactTailor, including but not limited to: loss of business, loss of revenue, contract disputes, or legal proceedings.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">6. Lawyer-Reviewed Templates</h2>
            <p>Certain premium templates are marked as "lawyer-reviewed." This means the template structure and language have been reviewed by a licensed attorney for general accuracy and common usage. It does <strong>not</strong> mean the template is guaranteed to be enforceable in your specific situation or jurisdiction. You remain solely responsible for any contract you sign or use commercially.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">7. Seek Professional Advice</h2>
            <p>We strongly encourage you to seek advice from a licensed attorney before:</p>
            <ul className="list-disc pl-5 mt-2 space-y-1">
              <li>Using any generated contract for significant commercial transactions</li>
              <li>Adapting templates for use in unfamiliar jurisdictions</li>
              <li>Relying on contract language in a dispute or litigation</li>
              <li>Using templates for employment, real estate, or financial agreements</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">8. Changes to This Disclaimer</h2>
            <p>PactTailor reserves the right to update this Disclaimer at any time. Continued use of the service after changes constitutes acceptance of the updated terms.</p>
          </section>

        </div>

        <div className="mt-10 pt-6 border-t border-gray-200 flex flex-wrap gap-4 text-sm">
          <Link href="/legal/terms" className="text-indigo-600 hover:underline">Terms of Service</Link>
          <Link href="/legal/privacy" className="text-indigo-600 hover:underline">Privacy Policy</Link>
          <a href="mailto:hello@pacttailor.com" className="text-gray-500 hover:text-gray-700">hello@pacttailor.com</a>
        </div>
      </div>
    </div>
  );
}
