export const CHANGELOG_ENTRIES = [
  {
    version: '1.6.0',
    date: '2025-06-12',
    tag: 'feature',
    title: 'Landing A/B Variants + Performance Tuning',
    items: [
      'Launched 3 landing page variants (ROI-first, Zero-Friction, Pricing Lab) with PostHog experiment tracking',
      'Dashboard summary API now cached with 30s TTL — TTFB down to <85ms on all core routes',
      'Added Supabase covering indexes on transactions and time_entries for 40% query speedup',
      'New /api/perf probe endpoint for p95 TTFB monitoring',
      'Playwright E2E smoke suite: 54 tests covering all 3 landing variants, CTA clicks, nav, A11y',
    ],
  },
  {
    version: '1.5.0',
    date: '2025-05-28',
    tag: 'feature',
    title: 'Import UX Overhaul + CSV Auto-Detection',
    items: [
      'Auto-detected CSV formats: Stripe Balance History, PayPal Activity, Upwork Transaction — no column mapping required',
      'Smart defaults: Amount is the only required field. Date defaults to today if missing.',
      'Yellow callout banner on import page explaining the minimum-friction mapping model',
      'Import preview now shows confidence score per column match',
      'Added support for multi-currency CSV imports (GBP, EUR, CAD auto-converted)',
    ],
  },
  {
    version: '1.4.0',
    date: '2025-05-12',
    tag: 'feature',
    title: 'Activation Funnel Tracking + Onboarding Copy',
    items: [
      'PostHog funnel events for all 7 activation steps (signup → first ROI view)',
      'Onboarding checklist redesigned with progress indicators and celebration state',
      'Demo data load button — pre-seeds 3 sample income streams for instant aha moment',
      'Funnel report API: GET /api/funnel/report returns step conversion rates',
      'New conversion-optimized copy across onboarding flow',
    ],
  },
  {
    version: '1.3.0',
    date: '2025-04-24',
    tag: 'feature',
    title: 'Pricing Experiments + AI Insights',
    items: [
      'A/B pricing experiment runner with statistical significance indicator',
      'AI income insights (Vercel AI Gateway / Claude Sonnet) — plain-language analysis of your ROI data',
      'Price-to-hit-target wizard: enter income goal, get recommended rate per stream',
      'Benchmark rate comparison widget (Pro) — see where you rank vs. anonymized peers',
    ],
  },
  {
    version: '1.2.0',
    date: '2025-04-10',
    tag: 'feature',
    title: 'Earnings Heatmap + Calendar Import',
    items: [
      'Earnings heatmap: 7×18 day/hour grid showing income-per-hour patterns',
      'ICS calendar import — Google Calendar and Apple Calendar exports auto-parsed',
      'Heatmap filter by income stream and date range',
      'Stream comparison mode: side-by-side heatmaps for two streams',
    ],
  },
  {
    version: '1.1.0',
    date: '2025-03-28',
    tag: 'feature',
    title: 'Timer + ROI Dashboard',
    items: [
      'One-tap mobile timer with stream assignment',
      'True hourly rate calculation per stream (net revenue ÷ tracked hours)',
      'Acquisition ROI module: track ad spend or platform fees against stream revenue',
      'Stripe and PayPal native import connectors',
      'ROI dashboard with 30/60/90-day date range selectors',
    ],
  },
  {
    version: '1.0.0',
    date: '2025-03-14',
    tag: 'launch',
    title: 'Initial Launch',
    items: [
      'Core CSV import with manual column mapping',
      'Income stream management (create, color-code, archive)',
      'Basic earnings timeline chart',
      'Supabase auth with email/password and magic link',
      'Stripe billing: Free tier (2 streams) and Pro plan ($29/mo)',
    ],
  },
]
