import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase'

export const CONSENT_VERSION = 'v1.0-2026-04-12'

export const CONSENT_ITEMS: Record<string, string> = {
  ai_disclaimer:
    'I understand that the permit packet generated by ExpediteHub is AI-assisted and may contain errors. A licensed professional will review it before submission, but final accuracy is my responsibility. Municipality acceptance is not guaranteed.',
  manual_confirmation:
    'I understand that electronic submission to the municipality may require a manual confirmation step by a licensed expediter, and that processing times are estimates only.',
  tos_agree:
    'I have read and agree to the ExpediteHub Terms of Service (expeditehub.com/tos) and Privacy Policy.',
  data_use:
    'I consent to ExpediteHub sharing my project details with vetted, licensed Austin permit expediters for the purpose of quoting and permit processing.',
}

export async function POST(req: NextRequest) {
  const db = getSupabaseAdmin()
  const body = await req.json()
  const { project_id, email, items_accepted, page_url } = body as {
    project_id?: string
    email: string
    items_accepted: string[]
    page_url?: string
  }

  if (!email || !items_accepted?.length) {
    return NextResponse.json({ error: 'email and items_accepted required' }, { status: 400 })
  }

  // Serialize the consent text at the time of acceptance (tamper-evident log)
  const consent_text = Object.fromEntries(
    items_accepted.map(k => [k, CONSENT_ITEMS[k] ?? k])
  )

  const ip = req.headers.get('x-forwarded-for') ?? req.headers.get('x-real-ip') ?? null
  const user_agent = req.headers.get('user-agent') ?? null

  const { data, error } = await db.from('consent_logs').insert({
    project_id: project_id ?? null,
    email,
    consent_version: CONSENT_VERSION,
    items_accepted,
    ip_address: ip,
    user_agent,
    page_url: page_url ?? null,
    consent_text,
    metro: 'Austin',
  }).select('id').single()

  if (error) {
    console.error('[consent] insert error:', error.message)
    return NextResponse.json({ error: error.message }, { status: 500 })
  }

  return NextResponse.json({ ok: true, consent_id: data?.id })
}
