import type { Metadata } from 'next'
import { Suspense } from 'react'
import Link from 'next/link'
import GalleryGrid from '@/components/GalleryGrid'

export const metadata: Metadata = {
  title: 'Coloring Pages Gallery — KidColoring',
  description: 'Browse hundreds of personalised coloring pages created by kids around the world. Get inspired and create your own free coloring book!',
  openGraph: {
    title: 'Kids Coloring Pages Gallery — KidColoring',
    description: 'Browse personalised coloring pages created by kids worldwide. Create yours free!',
    images: [{ url: 'https://kidcoloring-research.vercel.app/og-image.png', width: 1200, height: 630 }],
  },
  alternates: { canonical: 'https://kidcoloring-research.vercel.app/gallery' },
}

export default function GalleryPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-violet-50 to-white">
      {/* Header */}
      <header className="border-b border-violet-100 bg-white/80 backdrop-blur sticky top-0 z-10">
        <div className="max-w-6xl mx-auto px-6 py-3 flex items-center justify-between">
          <Link href="/" className="text-xl font-extrabold text-violet-700">
            🎨 KidColoring
          </Link>
          <Link href="/create/interests"
            className="bg-violet-600 text-white font-bold px-4 py-2 rounded-xl text-sm hover:bg-violet-700 transition-colors">
            Create yours free →
          </Link>
        </div>
      </header>

      <main className="max-w-6xl mx-auto px-6 py-12">
        {/* Hero */}
        <div className="text-center mb-10">
          <h1 className="text-4xl sm:text-5xl font-extrabold text-gray-900 mb-4">
            🌟 Community Gallery
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Personalised coloring pages created by kids worldwide. Every book is unique —
            made from <em>their</em> interests, heroes, and stories.
          </p>
          <div className="flex flex-wrap justify-center gap-3 mt-6">
            {['dinosaurs','unicorns','space','robots','dragons','mermaids','puppies','kittens'].map(theme => (
              <Link key={theme} href={`/gallery?theme=${theme}`}
                className="text-sm bg-white border border-violet-200 text-violet-700 font-semibold px-3 py-1.5 rounded-full hover:bg-violet-50 transition-colors capitalize">
                {theme}
              </Link>
            ))}
          </div>
        </div>

        {/* Gallery Grid */}
        <Suspense fallback={<GalleryGridSkeleton />}>
          <GalleryGrid />
        </Suspense>

        {/* CTA */}
        <div className="mt-16 text-center bg-gradient-to-r from-violet-600 to-purple-600 rounded-3xl p-10 text-white">
          <h2 className="text-3xl font-extrabold mb-3">Create your child&apos;s book in 2 minutes</h2>
          <p className="text-violet-100 text-lg mb-6">
            Free to try · 4 personalised pages · No account needed
          </p>
          <Link href="/create/interests"
            className="bg-white text-violet-700 font-extrabold px-8 py-4 rounded-2xl text-lg inline-block hover:bg-violet-50 transition-colors">
            Start creating for free →
          </Link>
        </div>

        {/* SEO text */}
        <div className="mt-12 text-center text-sm text-gray-400 max-w-2xl mx-auto">
          <p>
            All coloring pages are generated by AI and reviewed for child safety.
            Images shown with permission from parents who opted in to share.
            Want your child&apos;s page featured? Share it during the creation flow.
          </p>
        </div>
      </main>
    </div>
  )
}

function GalleryGridSkeleton() {
  return (
    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4">
      {Array.from({ length: 12 }).map((_, i) => (
        <div key={i} className="bg-gray-100 rounded-2xl aspect-square animate-pulse" />
      ))}
    </div>
  )
}
