export const HYPOTHESIS_GRID = {
  icps: [
    {
      id: "icp-1",
      name: "E-commerce Growth Teams",
      icon: "🛒",
      priority: "primary",
      description: "DTC or marketplace brands with $1M–$50M ARR using Shopify + Stripe + logistics tools, growing fast, lean ops team.",
      keyTools: ["Shopify", "Stripe", "ShipBob", "Klaviyo", "Meta Ads", "Google Ads"],
      painPoints: [
        "Shopify checkout changes break conversion flows overnight",
        "Stripe fee changes silently erode margins",
        "Klaviyo email policy changes affect deliverability",
        "No one tracks vendor ToS changes proactively",
      ],
    },
    {
      id: "icp-2",
      name: "B2B SaaS Ops/Engineering",
      icon: "🔧",
      priority: "primary",
      description: "SaaS companies with 10–200 employees where engineering or ops owns the vendor stack. AWS, GitHub, Stripe, Twilio.",
      keyTools: ["AWS", "GitHub", "Stripe", "Twilio", "Okta", "Datadog", "PagerDuty"],
      painPoints: [
        "AWS API deprecations discovered only when things break",
        "Okta auth changes cause production incidents",
        "Twilio messaging policy updates affect deliverability",
        "No single source of truth for vendor change risk",
      ],
    },
    {
      id: "icp-3",
      name: "Multi-Client Agencies",
      icon: "🏢",
      priority: "secondary",
      description: "Digital agencies managing 10–50 client tech stacks. Need to monitor tools across all clients for risk.",
      keyTools: ["Shopify", "Google Workspace", "Meta Ads", "HubSpot", "Mailchimp", "WooCommerce"],
      painPoints: [
        "Can't track vendor changes across 30+ client stacks",
        "Meta Ads policy changes impact campaign performance",
        "Google Workspace changes affect client workflows",
        "Client discovery of issues before agency = trust damage",
      ],
    },
    {
      id: "icp-4",
      name: "CFO/Finance-Led Compliance",
      icon: "⚖️",
      priority: "secondary",
      description: "Finance or legal teams at mid-market companies who own SaaS spend and compliance risk.",
      keyTools: ["Stripe", "QuickBooks", "Xero", "Chargebee", "Salesforce", "DocuSign"],
      painPoints: [
        "Payment processor fee changes hit P&L without warning",
        "Accounting tool API changes break automated reporting",
        "ToS updates create undetected compliance exposure",
        "No audit trail of when vendor terms changed",
      ],
    },
    {
      id: "icp-5",
      name: "Startup CTOs",
      icon: "🚀",
      priority: "tertiary",
      description: "Technical co-founders at seed-to-Series A startups managing a full modern stack.",
      keyTools: ["Vercel", "Supabase", "Stripe", "AWS", "GitHub", "Cloudflare"],
      painPoints: [
        "Too busy to read every vendor changelog",
        "Pricing changes hit burn rate without notice",
        "Security policy changes create audit failures",
      ],
    },
  ],

  problems: [
    {
      id: "p-1",
      statement: "Companies discover vendor changes reactively—only when something breaks or costs spike.",
      evidence: "Validated by Stripe's 2024 checkout update impacting 40% of integrations; most learned via support tickets.",
      severity: "critical",
      validationStatus: "hypothesis",
    },
    {
      id: "p-2",
      statement: "No tool exists that monitors multiple vendor changelogs and classifies changes by business risk.",
      evidence: "Market research shows only point solutions (AWS Health, Stripe Dashboard) per vendor, no cross-vendor risk layer.",
      severity: "high",
      validationStatus: "hypothesis",
    },
    {
      id: "p-3",
      statement: "Pricing and ToS changes are the most damaging but least tracked category of vendor change.",
      evidence: "Legal/finance teams rarely have engineering bandwidth to monitor API docs; changelog RSS feeds bury pricing changes.",
      severity: "high",
      validationStatus: "hypothesis",
    },
    {
      id: "p-4",
      statement: "Operations teams lack a shared view of vendor change risk across the whole stack.",
      evidence: "Information silos: eng tracks API docs, finance tracks invoices, legal reviews ToS manually once a year.",
      severity: "high",
      validationStatus: "hypothesis",
    },
    {
      id: "p-5",
      statement: "API deprecations cost mid-market companies average $47K per incident in emergency engineering.",
      evidence: "Based on Gartner 2023 report on unplanned technical debt; specific to SaaS API dependency failures.",
      severity: "critical",
      validationStatus: "to-validate",
    },
    {
      id: "p-6",
      statement: "Security policy changes from vendors (e.g., Okta, Auth0) create undiscovered compliance gaps.",
      evidence: "Okta 2022/2023 incidents where customers were unaware of scope changes until breach disclosure.",
      severity: "critical",
      validationStatus: "hypothesis",
    },
    {
      id: "p-7",
      statement: "Agencies waste significant time manually checking vendor updates for clients.",
      evidence: "Agency workflows rely on ad-hoc monitoring (RSS + bookmarks); no systematized tracking.",
      severity: "medium",
      validationStatus: "to-validate",
    },
  ],

  values: [
    {
      id: "v-1",
      icon: "⚡",
      title: "Early warning, plain English",
      icp: "All ICPs",
      description: "Instead of reading 20 changelogs, get one daily digest of changes that matter to YOUR stack—written in business language, not developer jargon.",
      confidence: "high",
    },
    {
      id: "v-2",
      icon: "💰",
      title: "Pricing & margin protection",
      icp: "E-commerce + CFO",
      description: "Be the first to know when Stripe, PayPal, or Shopify change fees. Model the impact before it hits your P&L.",
      confidence: "high",
    },
    {
      id: "v-3",
      icon: "🔒",
      title: "Security posture awareness",
      icp: "B2B SaaS + CTOs",
      description: "When Okta, AWS, or GitHub change authentication or permission requirements, know before it becomes a vulnerability or audit failure.",
      confidence: "medium",
    },
    {
      id: "v-4",
      icon: "📋",
      title: "Compliance & legal risk detection",
      icp: "CFO/Legal",
      description: "Automatic ToS and privacy policy diff tracking. Know when your vendor agreements change and what clauses shifted.",
      confidence: "medium",
    },
    {
      id: "v-5",
      icon: "🏢",
      title: "Multi-client risk dashboard",
      icp: "Agencies",
      description: "Single pane of glass for all client tool stacks. Be the hero who warns clients before changes hurt their business.",
      confidence: "medium",
    },
    {
      id: "v-6",
      icon: "🔗",
      title: "Cross-vendor risk correlation",
      icp: "B2B SaaS",
      description: "When Stripe + Shopify both change webhook formats in the same sprint, you need to know they interact. We surface correlated risks.",
      confidence: "low",
    },
  ],

  channels: [
    {
      id: "ch-1",
      icon: "💼",
      name: "LinkedIn Founder Outreach",
      priority: "primary",
      description: "Direct outreach to CTOs, Heads of Engineering, VP Ops at Series A–C SaaS companies with known Stripe/AWS/Shopify dependencies.",
      cost: "Time only",
      timeToResults: "1–2 weeks",
    },
    {
      id: "ch-2",
      icon: "🗺️",
      name: "Hacker News (Show HN / comments)",
      priority: "primary",
      description: "Post the Observatory as a free public tool. HN audience matches ICP-2 (SaaS eng) perfectly.",
      cost: "Time only",
      timeToResults: "1 day",
    },
    {
      id: "ch-3",
      icon: "📝",
      name: "SEO Content (Vendor Change Coverage)",
      priority: "primary",
      description: "Publish plain-English summaries of every major vendor change. Rank for '[vendor] api changes 2025' queries.",
      cost: "Low",
      timeToResults: "4–8 weeks",
    },
    {
      id: "ch-4",
      icon: "🐦",
      name: "Twitter/X Tech Community",
      priority: "secondary",
      description: "Tweet notable vendor changes as discovered. Build following among dev/ops audience by being first to surface changes.",
      cost: "Time only",
      timeToResults: "2–4 weeks",
    },
    {
      id: "ch-5",
      icon: "💬",
      name: "Slack/Discord Communities",
      priority: "secondary",
      description: "Indie Hackers, SaaS founders Slack groups, Shopify Partners community. Share observatory updates.",
      cost: "Time only",
      timeToResults: "1–2 weeks",
    },
    {
      id: "ch-6",
      icon: "🤝",
      name: "Agency & Consultant Partnerships",
      priority: "tertiary",
      description: "Partner with Shopify partners and AWS consulting partners. Revenue share on referrals.",
      cost: "Medium",
      timeToResults: "4–8 weeks",
    },
  ],

  pricing: [
    {
      tier: "Starter",
      price: "$99",
      period: "/mo",
      hypothesis: "SMBs and indie hackers will pay $99/mo for monitoring 10 tools with weekly email digests.",
      icp: "Startup CTOs",
      wtpSignal: "Need 5 customer interviews to validate",
      status: "hypothesis",
    },
    {
      tier: "Growth",
      price: "$299",
      period: "/mo",
      hypothesis: "Growth-stage SaaS teams will pay $299/mo for real-time Slack alerts + API access + 30 tools.",
      icp: "B2B SaaS Ops",
      wtpSignal: "Need 10 customer interviews + 10 deposits to validate",
      status: "hypothesis",
    },
    {
      tier: "Enterprise",
      price: "Custom",
      period: "",
      hypothesis: "$2,000–$5,000/mo for enterprises needing unlimited tools, SSO, and compliance reporting.",
      icp: "Enterprise Ops/Finance",
      wtpSignal: "Need 3 enterprise conversations to validate",
      status: "hypothesis",
    },
  ],
};
