export const RISK_TAXONOMY: RiskEvent[] = [
  // ─── PRICING CHANGES ──────────────────────────────────────────────────────
  {
    id: "PRICE-001",
    category: "pricing",
    title: "Payment Processing Fee Increase",
    description: "Vendor raises per-transaction fees, interchange rates, or monthly minimums on payment processing.",
    examples: ["Stripe increases card processing from 2.9%+30¢ to 3.2%+35¢", "PayPal adds new cross-border fee tier"],
    impactedRoles: ["CFO", "Finance", "Founder"],
    riskLevel: "high",
    detectionMethod: "pricing_page_diff",
    detectionUrls: ["https://stripe.com/pricing", "https://www.paypal.com/us/business/paypal-business-fees"],
    typicalLeadTime: "0–30 days",
    vendors: ["Stripe", "PayPal", "Braintree", "Square", "Chargebee", "Recurly"],
  },
  {
    id: "PRICE-002",
    category: "pricing",
    title: "SaaS Subscription Tier Restructuring",
    description: "Vendor restructures pricing tiers, moves features between plans, or removes grandfathered pricing.",
    examples: ["HubSpot moves Marketing Hub contacts limit from 10K to 2K on Starter", "Salesforce retires legacy SKUs"],
    impactedRoles: ["CFO", "Ops", "CTO"],
    riskLevel: "high",
    detectionMethod: "pricing_page_diff",
    detectionUrls: ["https://www.hubspot.com/pricing", "https://www.salesforce.com/editions-pricing/"],
    typicalLeadTime: "30–90 days notice",
    vendors: ["HubSpot", "Salesforce", "Intercom", "Zendesk", "Mailchimp"],
  },
  {
    id: "PRICE-003",
    category: "pricing",
    title: "Cloud Compute/Storage Pricing Change",
    description: "AWS, GCP, or Azure changes EC2, S3, Lambda, or egress pricing.",
    examples: ["AWS reduces S3 PUT costs", "AWS increases EC2 On-Demand pricing in eu-west"],
    impactedRoles: ["Engineering", "FinOps", "CTO"],
    riskLevel: "medium",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://aws.amazon.com/pricing/", "https://aws.amazon.com/new/"],
    typicalLeadTime: "0–60 days",
    vendors: ["AWS", "GCP", "Azure"],
  },
  {
    id: "PRICE-004",
    category: "pricing",
    title: "API Rate Limit or Quota Reduction",
    description: "Vendor tightens API call limits, reduces free tier quotas, or introduces overage charges.",
    examples: ["OpenAI reduces free API quota", "Twilio adds new messaging pricing by country"],
    impactedRoles: ["Engineering", "Product", "CTO"],
    riskLevel: "high",
    detectionMethod: "docs_diff",
    detectionUrls: ["https://platform.openai.com/docs/guides/rate-limits", "https://www.twilio.com/pricing"],
    typicalLeadTime: "7–30 days",
    vendors: ["Twilio", "SendGrid", "Mailgun", "OpenAI", "Google Maps"],
  },
  {
    id: "PRICE-005",
    category: "pricing",
    title: "Platform Transaction Fee Introduction",
    description: "Marketplace or platform adds a new transaction fee for services previously free.",
    examples: ["Shopify adds 2% fee for non-Shopify Payments", "App store transaction fee for in-app purchases"],
    impactedRoles: ["Finance", "Founder", "Ops"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://www.shopify.com/pricing", "https://shopify.dev/changelog"],
    typicalLeadTime: "0–60 days",
    vendors: ["Shopify", "WooCommerce", "BigCommerce"],
  },
  {
    id: "PRICE-006",
    category: "pricing",
    title: "Storage Tier or Data Egress Cost Change",
    description: "Changes to storage pricing caps, egress costs, or data retention pricing.",
    examples: ["Supabase changes storage egress pricing", "Cloudflare adds R2 egress fees"],
    impactedRoles: ["Engineering", "FinOps"],
    riskLevel: "medium",
    detectionMethod: "pricing_page_diff",
    detectionUrls: ["https://supabase.com/pricing", "https://developers.cloudflare.com/r2/pricing/"],
    typicalLeadTime: "30–90 days",
    vendors: ["Supabase", "Cloudflare", "AWS", "Vercel", "Netlify"],
  },

  // ─── LEGAL & COMPLIANCE ───────────────────────────────────────────────────
  {
    id: "LEGAL-001",
    category: "legal",
    title: "Terms of Service Material Update",
    description: "Vendor modifies ToS in ways that affect liability, data ownership, auto-renewal terms, or indemnification.",
    examples: ["Slack updates ToS to allow training AI on messages", "Zoom ToS arbitration clause change"],
    impactedRoles: ["Legal", "CFO", "CEO"],
    riskLevel: "high",
    detectionMethod: "tos_diff",
    detectionUrls: ["https://slack.com/intl/en-us/terms-of-service", "https://explore.zoom.us/en/terms/"],
    typicalLeadTime: "0–30 days",
    vendors: ["Slack", "Zoom", "Google Workspace", "Microsoft 365", "Dropbox"],
  },
  {
    id: "LEGAL-002",
    category: "legal",
    title: "Privacy Policy Change Affecting Data Processing",
    description: "Vendor updates how they collect, share, or process user/company data.",
    examples: ["Google Workspace updates data retention clauses", "HubSpot changes third-party data sharing"],
    impactedRoles: ["Legal", "Compliance", "DPO"],
    riskLevel: "high",
    detectionMethod: "tos_diff",
    detectionUrls: ["https://policies.google.com/privacy", "https://legal.hubspot.com/privacy-policy"],
    typicalLeadTime: "0–30 days",
    vendors: ["Google Workspace", "Salesforce", "HubSpot", "Zoom", "Microsoft 365"],
  },
  {
    id: "LEGAL-003",
    category: "legal",
    title: "Data Processing Agreement (DPA) Update",
    description: "Vendor changes subprocessors, data locations, or GDPR/CCPA data processing terms.",
    examples: ["Stripe adds new subprocessors in APAC", "Okta DPA update for EU data residency"],
    impactedRoles: ["Legal", "DPO", "Compliance"],
    riskLevel: "high",
    detectionMethod: "tos_diff",
    detectionUrls: ["https://stripe.com/legal/dpa", "https://www.okta.com/privacy/"],
    typicalLeadTime: "30 days",
    vendors: ["Stripe", "Okta", "Auth0", "Salesforce", "HubSpot"],
  },
  {
    id: "LEGAL-004",
    category: "legal",
    title: "Acceptable Use Policy Change",
    description: "Vendor restricts what content, industries, or use cases are permitted on their platform.",
    examples: ["Stripe bans new merchant category", "Twilio restricts SMS for certain use cases"],
    impactedRoles: ["Legal", "Product", "Ops"],
    riskLevel: "high",
    detectionMethod: "tos_diff",
    detectionUrls: ["https://stripe.com/restricted-businesses", "https://www.twilio.com/legal/aup"],
    typicalLeadTime: "0–30 days",
    vendors: ["Stripe", "Twilio", "PayPal", "Shopify", "AWS"],
  },
  {
    id: "LEGAL-005",
    category: "legal",
    title: "Compliance Certification Lapse or Change",
    description: "Vendor loses or changes a key compliance certification (SOC 2, ISO 27001, HIPAA BAA).",
    examples: ["Vendor SOC 2 Type II lapses", "AWS adds new HIPAA-eligible services"],
    impactedRoles: ["CISO", "Legal", "Compliance"],
    riskLevel: "high",
    detectionMethod: "trust_page_diff",
    detectionUrls: ["https://aws.amazon.com/compliance/", "https://stripe.com/docs/security"],
    typicalLeadTime: "0 days (immediate).",
    vendors: ["AWS", "Stripe", "Google Workspace", "Okta", "Salesforce"],
  },
  {
    id: "LEGAL-006",
    category: "legal",
    title: "Auto-Renewal or Contract Term Change",
    description: "Vendor changes default contract length, auto-renewal windows, or cancellation notice requirements.",
    examples: ["SaaS vendor changes annual auto-renewal notice from 30 to 15 days"],
    impactedRoles: ["Finance", "Legal", "Procurement"],
    riskLevel: "medium",
    detectionMethod: "tos_diff",
    detectionUrls: [],
    typicalLeadTime: "30–90 days",
    vendors: ["Salesforce", "HubSpot", "Zendesk", "Adobe", "DocuSign"],
  },

  // ─── OPERATIONAL / API CHANGES ───────────────────────────────────────────
  {
    id: "OPS-001",
    category: "operational",
    title: "API Endpoint Deprecation Notice",
    description: "Vendor announces retirement of one or more API endpoints with a specific sunset date.",
    examples: ["Stripe deprecates Sources API in favor of PaymentIntents", "Twilio retires legacy REST API version"],
    impactedRoles: ["Engineering", "CTO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://stripe.com/docs/changelog", "https://www.twilio.com/changelog"],
    typicalLeadTime: "3–12 months",
    vendors: ["Stripe", "Twilio", "Shopify", "Salesforce", "HubSpot"],
  },
  {
    id: "OPS-002",
    category: "operational",
    title: "Webhook Payload Format Change",
    description: "Vendor changes the structure, fields, or delivery mechanism of webhook events.",
    examples: ["Stripe changes webhook event object structure", "GitHub changes webhook payload for push events"],
    impactedRoles: ["Engineering", "DevOps"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://stripe.com/docs/changelog", "https://github.blog/changelog/"],
    typicalLeadTime: "30–90 days",
    vendors: ["Stripe", "GitHub", "Shopify", "Intercom", "PagerDuty"],
  },
  {
    id: "OPS-003",
    category: "operational",
    title: "SDK Major Version Breaking Change",
    description: "Vendor releases a major SDK version with breaking changes requiring code migration.",
    examples: ["Stripe SDK v12 removes legacy Node.js patterns", "AWS SDK v3 mandatory migration"],
    impactedRoles: ["Engineering", "CTO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://github.com/stripe/stripe-node/releases", "https://github.com/aws/aws-sdk-js-v3/releases"],
    typicalLeadTime: "6–12 months",
    vendors: ["Stripe", "AWS", "Twilio", "Salesforce", "Okta"],
  },
  {
    id: "OPS-004",
    category: "operational",
    title: "OAuth Scope or Permission Change",
    description: "Vendor changes required OAuth scopes, permission grants, or access token behavior.",
    examples: ["Google Workspace restricts Sheets API scopes", "Slack changes OAuth 2.0 scope requirements"],
    impactedRoles: ["Engineering", "Security"],
    riskLevel: "high",
    detectionMethod: "docs_diff",
    detectionUrls: ["https://developers.google.com/identity/protocols/oauth2/scopes", "https://api.slack.com/scopes"],
    typicalLeadTime: "30–90 days",
    vendors: ["Google Workspace", "Slack", "GitHub", "Salesforce", "HubSpot"],
  },
  {
    id: "OPS-005",
    category: "operational",
    title: "Service Region or Data Center Change",
    description: "Vendor adds, removes, or migrates service regions affecting latency or data residency.",
    examples: ["AWS deprecates us-east-1 availability zone", "Shopify migrates EU merchants to new data center"],
    impactedRoles: ["Engineering", "Legal", "Compliance"],
    riskLevel: "medium",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://aws.amazon.com/new/", "https://shopify.dev/changelog"],
    typicalLeadTime: "60–180 days",
    vendors: ["AWS", "GCP", "Azure", "Shopify", "Cloudflare"],
  },
  {
    id: "OPS-006",
    category: "operational",
    title: "Checkout Flow or UX Breaking Change",
    description: "E-commerce platform modifies checkout flow in ways that break custom integrations or conversion tracking.",
    examples: ["Shopify deprecates checkout.liquid for checkout extensibility API", "Stripe Elements design system change"],
    impactedRoles: ["Engineering", "Product", "Growth"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://shopify.dev/changelog", "https://stripe.com/docs/changelog"],
    typicalLeadTime: "30–90 days",
    vendors: ["Shopify", "Stripe", "WooCommerce", "BigCommerce"],
  },
  {
    id: "OPS-007",
    category: "operational",
    title: "App Permission or Marketplace Policy Change",
    description: "App store or marketplace changes what data third-party apps can access or required permission scopes.",
    examples: ["Shopify app permissions model change", "Google Workspace Marketplace policy update"],
    impactedRoles: ["Engineering", "Product", "Legal"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://shopify.dev/docs/apps/build/authentication-authorization/access-scopes", "https://developers.google.com/workspace/marketplace"],
    typicalLeadTime: "30–60 days",
    vendors: ["Shopify", "Google Workspace", "Salesforce AppExchange", "HubSpot App Marketplace"],
  },
  {
    id: "OPS-008",
    category: "operational",
    title: "Email/SMS Deliverability Policy Change",
    description: "Email or SMS provider changes sending limits, required authentication (DMARC/DKIM), or carrier filtering rules.",
    examples: ["Gmail announces DMARC requirements for bulk senders", "Twilio updates A2P 10DLC registration requirements"],
    impactedRoles: ["Marketing", "Engineering", "Growth"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://support.google.com/a/answer/81126", "https://www.twilio.com/docs/messaging/compliance"],
    typicalLeadTime: "30–90 days",
    vendors: ["Google Workspace", "Twilio", "SendGrid", "Mailchimp", "Klaviyo"],
  },
  {
    id: "OPS-009",
    category: "operational",
    title: "Logistics API or Shipping Rate Change",
    description: "Carrier or logistics platform changes API structure, rate calculations, or label generation.",
    examples: ["FedEx API v2 deprecation", "UPS changes dimensional weight formula"],
    impactedRoles: ["Ops", "Engineering", "Finance"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://developer.fedex.com/api/en-us/get-started/whats-new.html"],
    typicalLeadTime: "90–180 days",
    vendors: ["FedEx", "UPS", "USPS", "ShipBob", "EasyPost"],
  },
  {
    id: "OPS-010",
    category: "operational",
    title: "Payroll or HR Platform Compliance Update",
    description: "Payroll vendor updates tax tables, compliance rules, or benefits integration requirements.",
    examples: ["Gusto updates W-2 filing API structure", "ADP changes direct deposit routing format"],
    impactedRoles: ["HR", "Finance", "Engineering"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: [],
    typicalLeadTime: "30–90 days",
    vendors: ["Gusto", "ADP", "Rippling", "Paychex", "QuickBooks Payroll"],
  },
  {
    id: "OPS-011",
    category: "operational",
    title: "Ad Platform Targeting or Attribution Change",
    description: "Advertising platform changes audience targeting, attribution windows, or conversion tracking.",
    examples: ["Meta removes 28-day attribution window", "Google Ads deprecates similar audiences"],
    impactedRoles: ["Marketing", "Growth", "Finance"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://developers.facebook.com/docs/marketing-api/changelog/", "https://developers.google.com/google-ads/api/docs/release-notes"],
    typicalLeadTime: "30–90 days",
    vendors: ["Meta Ads", "Google Ads", "TikTok Ads", "LinkedIn Ads"],
  },
  {
    id: "OPS-012",
    category: "operational",
    title: "Database or Infrastructure Service Sunset",
    description: "Cloud or DB provider announces end-of-life for a specific service, instance type, or runtime.",
    examples: ["AWS Lambda deprecates Node.js 14 runtime", "Heroku removes free dynos"],
    impactedRoles: ["Engineering", "DevOps", "CTO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html"],
    typicalLeadTime: "6–12 months",
    vendors: ["AWS", "Heroku", "GCP", "Azure", "Vercel"],
  },

  // ─── SECURITY ─────────────────────────────────────────────────────────────
  {
    id: "SEC-001",
    category: "security",
    title: "Authentication Method Requirement Change",
    description: "Vendor mandates new auth method, deprecates API key auth, or requires MFA/SSO.",
    examples: ["GitHub removes password auth for Git", "Okta mandates phishing-resistant MFA"],
    impactedRoles: ["Engineering", "IT", "CISO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://github.blog/changelog/", "https://developer.okta.com/docs/release-notes/"],
    typicalLeadTime: "30–90 days",
    vendors: ["GitHub", "Okta", "Auth0", "Google Workspace", "AWS"],
  },
  {
    id: "SEC-002",
    category: "security",
    title: "TLS/Cipher Suite Requirement Upgrade",
    description: "Vendor drops support for older TLS versions or cipher suites, requiring client-side upgrades.",
    examples: ["Stripe drops TLS 1.0/1.1 support", "AWS requires TLS 1.2+ for all API calls"],
    impactedRoles: ["Engineering", "DevOps", "CISO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: ["https://stripe.com/docs/changelog"],
    typicalLeadTime: "90–180 days",
    vendors: ["Stripe", "AWS", "GitHub", "Twilio", "Cloudflare"],
  },
  {
    id: "SEC-003",
    category: "security",
    title: "API Key Format or Rotation Policy Change",
    description: "Vendor changes API key format, adds mandatory rotation, or introduces key scoping requirements.",
    examples: ["Stripe updates publishable key prefix", "GitHub changes PAT format to fine-grained tokens"],
    impactedRoles: ["Engineering", "Security", "DevOps"],
    riskLevel: "medium",
    detectionMethod: "docs_diff",
    detectionUrls: ["https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github"],
    typicalLeadTime: "30–90 days",
    vendors: ["GitHub", "Stripe", "AWS", "SendGrid", "Twilio"],
  },
  {
    id: "SEC-004",
    category: "security",
    title: "Security Incident or Breach Notification",
    description: "Vendor discloses a data breach, security incident, or compromise affecting customer data.",
    examples: ["Okta discloses HAR file exposure", "LastPass announces breach of encrypted vaults"],
    impactedRoles: ["CISO", "Legal", "CEO"],
    riskLevel: "high",
    detectionMethod: "trust_page_diff",
    detectionUrls: ["https://trust.okta.com/", "https://status.stripe.com/"],
    typicalLeadTime: "0 days (immediate)",
    vendors: ["Okta", "LastPass", "GitHub", "Twilio", "Salesforce"],
  },
  {
    id: "SEC-005",
    category: "security",
    title: "RBAC/Permission Model Restructuring",
    description: "Vendor overhauls role-based access control, adding or removing permission scopes.",
    examples: ["AWS IAM policy syntax breaking change", "Salesforce profile permission deprecation"],
    impactedRoles: ["Engineering", "IT", "CISO"],
    riskLevel: "medium",
    detectionMethod: "docs_diff",
    detectionUrls: ["https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_actions-resources-contextkeys.html"],
    typicalLeadTime: "30–90 days",
    vendors: ["AWS", "Salesforce", "Okta", "Google Workspace", "GitHub"],
  },

  // ─── VENDOR RISK ──────────────────────────────────────────────────────────
  {
    id: "VENDOR-001",
    category: "vendor_risk",
    title: "Vendor Acquisition or Merger Announcement",
    description: "Key tool is acquired, merged, or undergoes ownership change that may affect roadmap, pricing, or continuity.",
    examples: ["Twilio acquires Segment", "Salesforce acquires Slack"],
    impactedRoles: ["CEO", "CTO", "CFO"],
    riskLevel: "high",
    detectionMethod: "news_monitor",
    detectionUrls: [],
    typicalLeadTime: "0 days (immediate)",
    vendors: ["All"],
  },
  {
    id: "VENDOR-002",
    category: "vendor_risk",
    title: "Product Line Discontinuation",
    description: "Vendor announces end-of-life for a specific product, feature set, or integration.",
    examples: ["Google deprecates Universal Analytics", "Heroku removes free tier"],
    impactedRoles: ["Engineering", "Ops", "CTO"],
    riskLevel: "high",
    detectionMethod: "changelog_scrape",
    detectionUrls: [],
    typicalLeadTime: "3–12 months",
    vendors: ["Google", "Heroku", "AWS", "Adobe", "Salesforce"],
  },
  {
    id: "VENDOR-003",
    category: "vendor_risk",
    title: "SLA Downgrade",
    description: "Vendor reduces uptime guarantees, support response times, or removes financial remedies from SLA.",
    examples: ["Vendor reduces uptime guarantee from 99.99% to 99.9%", "Support SLA response time doubled"],
    impactedRoles: ["Ops", "Legal", "CTO"],
    riskLevel: "medium",
    detectionMethod: "tos_diff",
    detectionUrls: [],
    typicalLeadTime: "30–90 days",
    vendors: ["AWS", "Shopify", "Salesforce", "HubSpot", "Zendesk"],
  },
  {
    id: "VENDOR-004",
    category: "vendor_risk",
    title: "Support Tier Change or Removal",
    description: "Vendor restructures support tiers, removes phone support, or makes enterprise support mandatory.",
    examples: ["Twilio removes phone support from standard tier", "Shopify changes Plus support hours"],
    impactedRoles: ["Ops", "Finance", "CTO"],
    riskLevel: "medium",
    detectionMethod: "pricing_page_diff",
    detectionUrls: [],
    typicalLeadTime: "30–90 days",
    vendors: ["Twilio", "Shopify", "AWS", "HubSpot", "Salesforce"],
  },
];

export type RiskEvent = {
  id: string;
  category: "pricing" | "legal" | "operational" | "security" | "vendor_risk";
  title: string;
  description: string;
  examples: string[];
  impactedRoles: string[];
  riskLevel: "high" | "medium" | "low";
  detectionMethod: "pricing_page_diff" | "changelog_scrape" | "tos_diff" | "docs_diff" | "trust_page_diff" | "news_monitor";
  detectionUrls: string[];
  typicalLeadTime: string;
  vendors: string[];
};

export const DETECTION_METHODS: Record<string, { label: string; description: string; icon: string }> = {
  pricing_page_diff: {
    label: "Pricing Page Diff",
    icon: "💰",
    description: "Daily snapshot + diff of vendor pricing pages. Detects text/number changes in pricing tables.",
  },
  changelog_scrape: {
    label: "Changelog Scrape",
    icon: "📋",
    description: "Scrapes vendor changelog URLs (RSS feeds, HTML pages). Extracts and classifies new entries.",
  },
  tos_diff: {
    label: "Terms of Service Diff",
    icon: "⚖️",
    description: "Daily snapshot + diff of ToS, privacy policy, DPA, and AUP pages. Flags material changes.",
  },
  docs_diff: {
    label: "Documentation Diff",
    icon: "📖",
    description: "Monitors API reference docs for endpoint additions, removals, parameter changes.",
  },
  trust_page_diff: {
    label: "Trust Page Diff",
    icon: "🔒",
    description: "Monitors vendor trust/status/compliance pages for certification and incident changes.",
  },
  news_monitor: {
    label: "News Monitor",
    icon: "📰",
    description: "Monitors press releases, TechCrunch, and vendor blogs for acquisition/EOL announcements.",
  },
};

export const CATEGORY_META: Record<string, { label: string; icon: string; color: string }> = {
  pricing: { label: "Pricing", icon: "💰", color: "#f59e0b" },
  legal: { label: "Legal & Compliance", icon: "⚖️", color: "#ef4444" },
  operational: { label: "Operational", icon: "🔧", color: "#6366f1" },
  security: { label: "Security", icon: "🔒", color: "#ef4444" },
  vendor_risk: { label: "Vendor Risk", icon: "🏢", color: "#8b5cf6" },
};
