import Link from 'next/link'

export const metadata = {
  title: 'Privacy Policy — BetaWindow',
  description: 'How BetaWindow collects, uses, and protects your personal data.',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white">
      <nav className="border-b border-gray-100 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-lg font-bold text-gray-900">BetaWindow</Link>
      </nav>
      <main className="max-w-3xl mx-auto px-6 py-16 prose prose-gray">
        <h1>Privacy Policy</h1>
        <p className="text-sm text-gray-500">Last updated: April 17, 2026</p>

        <p>BetaWindow (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the website at betawindow.com (the &quot;Service&quot;). This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our Service. By using BetaWindow, you agree to the practices described in this policy.</p>

        <h2>1. Information We Collect</h2>
        <h3>Information you provide directly:</h3>
        <ul>
          <li><strong>Account information:</strong> Email address and password when you create an account.</li>
          <li><strong>Payment information:</strong> Credit/debit card details are processed directly by Stripe, Inc. (our payment processor). We store only a Stripe customer ID and last-four digits; we do not store raw card numbers.</li>
          <li><strong>Tester payout information:</strong> Bank account details for Stripe Payouts are collected and processed by Stripe; we do not store your banking credentials.</li>
          <li><strong>Test job submissions:</strong> App URLs, test instructions, and any content you submit when creating a test job.</li>
          <li><strong>Feedback and reports:</strong> Text, screenshots, and structured data submitted by testers.</li>
        </ul>
        <h3>Information collected automatically:</h3>
        <ul>
          <li><strong>Usage data:</strong> Pages visited, clicks, session duration, feature interactions, and events — collected via PostHog analytics (only with your consent).</li>
          <li><strong>Device and connection data:</strong> IP address, browser type, operating system, and referring URL — collected via PostHog and Vercel infrastructure.</li>
          <li><strong>Marketing attribution:</strong> UTM parameters and campaign source data when you arrive from an advertisement or link.</li>
          <li><strong>Advertising conversion data:</strong> If you arrive from a Reddit advertisement and consent to analytics cookies, Reddit&apos;s conversion pixel may record your interaction. See Section 4 (Third-Party Services).</li>
        </ul>
        <h3>Test session data (unique to our platform):</h3>
        <p>When a tester runs a test on your submitted app URL, our platform automatically captures:</p>
        <ul>
          <li>A screen recording of the full tester session.</li>
          <li>All network requests made by the tested app (URL, HTTP method, status codes, response times).</li>
          <li>Browser console logs and JavaScript errors generated by the tested app.</li>
        </ul>
        <p>This captured data may incidentally contain personal information belonging to users of the app being tested. By submitting an app URL for testing, you represent that you have the right to authorize such data capture and that you will use only non-production or anonymized test environments wherever possible.</p>

        <h2>2. How We Use Your Information</h2>
        <ul>
          <li>To create and maintain your account.</li>
          <li>To process payments and tester payouts via Stripe.</li>
          <li>To match test jobs with available testers.</li>
          <li>To deliver test reports and session artifacts to requesters.</li>
          <li>To generate AI-powered summaries of test sessions (processed server-side).</li>
          <li>To improve our platform through analytics and usage data (PostHog, with consent).</li>
          <li>To send transactional emails (account confirmation, job status updates).</li>
          <li>To comply with legal obligations, including tax reporting (Form 1099-NEC/1099-K where applicable).</li>
          <li>To measure the effectiveness of our advertising campaigns (Reddit Pixel, with consent).</li>
        </ul>

        <h2>3. Data Retention</h2>
        <ul>
          <li><strong>Account data:</strong> Retained for the duration of your account and for 90 days after deletion request.</li>
          <li><strong>Test session recordings and logs:</strong> Retained for 90 days from job completion, then automatically deleted.</li>
          <li><strong>Payment records:</strong> Retained for 7 years as required by tax law.</li>
          <li><strong>Analytics data:</strong> Retained per PostHog&apos;s default retention settings (typically 1 year).</li>
        </ul>

        <h2>4. Third-Party Services</h2>
        <p>We share data with the following third-party service providers:</p>
        <ul>
          <li><strong>Stripe, Inc.</strong> — Payment processing and tester payouts. <a href="https://stripe.com/privacy" target="_blank" rel="noopener">Stripe Privacy Policy</a></li>
          <li><strong>Supabase, Inc.</strong> — Database, authentication, and email delivery. <a href="https://supabase.com/privacy" target="_blank" rel="noopener">Supabase Privacy Policy</a></li>
          <li><strong>PostHog, Inc.</strong> — Product analytics and session tracking (with your consent). PostHog may set cookies to identify your browser across sessions. <a href="https://posthog.com/privacy" target="_blank" rel="noopener">PostHog Privacy Policy</a></li>
          <li><strong>Reddit, Inc.</strong> — Advertising conversion tracking via Reddit Pixel (with your consent). Reddit may receive anonymized event data when you visit pages on our site. <a href="https://www.reddit.com/policies/privacy-policy" target="_blank" rel="noopener">Reddit Privacy Policy</a></li>
          <li><strong>Vercel, Inc.</strong> — Website hosting and infrastructure. <a href="https://vercel.com/legal/privacy-policy" target="_blank" rel="noopener">Vercel Privacy Policy</a></li>
        </ul>

        <h2>5. Cookies and Tracking Technologies</h2>
        <p>We use the following types of cookies:</p>
        <ul>
          <li><strong>Essential cookies:</strong> Required for authentication and core platform function (Supabase session cookies). These are always active.</li>
          <li><strong>Analytics cookies:</strong> PostHog sets cookies to track usage and improve our product. These are only set after you provide consent via our cookie banner.</li>
          <li><strong>Advertising cookies:</strong> Reddit Pixel may set cookies for ad conversion measurement. These are only set after you provide consent via our cookie banner. You can also opt out via Reddit&apos;s ad preferences.</li>
        </ul>
        <p>A cookie consent banner is displayed on your first visit. You may update your preferences at any time via the &quot;Cookie Settings&quot; link in our footer.</p>

        <h2>6. Your Rights</h2>
        <p>Depending on your location, you may have the following rights regarding your personal data:</p>
        <ul>
          <li><strong>Access:</strong> Request a copy of the personal data we hold about you.</li>
          <li><strong>Deletion:</strong> Request deletion of your account and associated personal data.</li>
          <li><strong>Correction:</strong> Request correction of inaccurate data.</li>
          <li><strong>Portability:</strong> Request your data in a machine-readable format.</li>
          <li><strong>Opt-out of sale/sharing (CCPA):</strong> We do not sell your personal data. You may opt out of data sharing for advertising purposes via our cookie consent tool.</li>
          <li><strong>Object to processing (GDPR):</strong> You may object to certain processing activities.</li>
        </ul>
        <p>To exercise any of these rights, contact us at <a href="mailto:hello@betawindow.com">hello@betawindow.com</a>. We will respond within 30 days.</p>

        <h2>7. Data Security</h2>
        <p>We implement industry-standard security measures including TLS encryption in transit, encrypted storage at rest via Supabase, and row-level security policies restricting data access by role. Passwords are hashed and never stored in plaintext. However, no system is 100% secure, and we cannot guarantee absolute security.</p>

        <h2>8. Children&apos;s Privacy</h2>
        <p>BetaWindow is not directed at users under 18 years of age. We do not knowingly collect personal information from minors. If you believe a minor has created an account, contact us at hello@betawindow.com and we will delete the account promptly.</p>

        <h2>9. International Data Transfers</h2>
        <p>Our servers are hosted in the United States (Vercel/Supabase US regions). If you access our Service from outside the United States, your data may be transferred to and processed in the United States. For EU/UK users, such transfers occur under applicable data transfer mechanisms (Standard Contractual Clauses where applicable via our sub-processors).</p>

        <h2>10. Changes to This Policy</h2>
        <p>We may update this Privacy Policy from time to time. We will notify you of material changes via email or a prominent notice on the Service at least 14 days before the change takes effect. Your continued use of the Service after notice constitutes acceptance of the updated policy.</p>

        <h2>11. Contact</h2>
        <p>For privacy questions or to exercise your rights, contact us at:<br/>
        BetaWindow<br/>
        2298 Johanna Court, Pinole, CA 94564<br/>
        Email: <a href="mailto:hello@betawindow.com">hello@betawindow.com</a></p>
      </main>
      <footer className="bg-gray-900 text-gray-400 py-8 px-6 text-center text-sm">
        <div className="flex flex-wrap justify-center gap-6 mb-4">
          <Link href="/privacy" className="hover:text-white">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-white">Terms of Service</Link>
          <Link href="/marketplace" className="hover:text-white">Marketplace</Link>
          <a href="mailto:hello@betawindow.com" className="hover:text-white">Contact</a>
        </div>
        <p>© {new Date().getFullYear()} BetaWindow · 2298 Johanna Court, Pinole, CA 94564 · <a href="mailto:hello@betawindow.com" className="hover:text-white">hello@betawindow.com</a></p>
      </footer>
    </div>
  )
}
