#!/usr/bin/env python3
"""Seed 50+ grant narrative templates into Supabase."""
import json, os, urllib.request, urllib.error

SUPABASE_URL = "https://zgqlnnftbkfnbtzlbaiy.supabase.co"
SUPABASE_KEY = os.environ["SUPABASE_ACCESS_TOKEN"]

TEMPLATES = [
  # ── HUD / CDBG ────────────────────────────────────────────────────────────────
  {"title":"CDBG Housing Rehabilitation — Statement of Need","funder_name":"HUD","funder_type":"federal","program_name":"Community Development Block Grant","cfda_number":"14.218","section_key":"needs_statement","section_title":"Statement of Need","org_types":["nonprofit","municipal"],"program_types":["housing","homelessness"],"tags":["CDBG","HUD","housing","low-income"],"win_count":12,"use_count":34,"typical_word_limit":750,"content_md":"According to the 2023 American Community Survey, [X]% of households in [Target Area] spend more than 30% of their income on housing costs, meeting HUD's definition of cost-burdened. Among owner-occupied units built before 1978, [X]% exhibit one or more serious deficiencies — including substandard electrical systems, failing roofs, or lead-based paint hazards — that pose direct risks to resident health and safety.\n\nThe [Target Area] housing stock is aging: [X]% of owner-occupied homes were built before 1960. For low-income homeowners — particularly elderly residents and households with children — the cost of critical repairs is prohibitive. The median home repair cost for identified units is $[X], compared to a median household income of $[X] for eligible households.\n\nWithout intervention, these households face forced displacement, deteriorating home values, and ongoing health risks. Our proposed rehabilitation program will address [X] units in the first program year, prioritizing households at or below 80% of Area Median Income (AMI) and owner-occupants aged 62 or older."},

  {"title":"CDBG Public Services — Youth Employment Program Need","funder_name":"HUD","funder_type":"federal","program_name":"Community Development Block Grant","cfda_number":"14.218","section_key":"needs_statement","section_title":"Statement of Need","org_types":["nonprofit","municipal"],"program_types":["youth","workforce"],"tags":["CDBG","HUD","youth","employment"],"win_count":8,"use_count":22,"typical_word_limit":600,"content_md":"Youth unemployment in [Target Area] stands at [X]%, more than double the county average of [X]% (Bureau of Labor Statistics, [Year]). Among youth ages 16–24 who are neither enrolled in school nor employed — known as 'disconnected youth' — the rate reaches [X]%, representing approximately [X] young people in our service area.\n\nDisconnected youth face compounding barriers: [X]% lack a high school diploma or GED; [X]% have justice-system involvement that creates employment barriers; and [X]% report lacking access to reliable transportation to employment sites.\n\nResearch consistently demonstrates that early employment intervention reduces long-term poverty, improves educational attainment, and reduces juvenile justice recidivism. The cost of youth disconnection — in lost productivity, increased social services, and justice involvement — is estimated at $[X] per disconnected youth over their lifetime (Measure of America, [Year]). Early intervention yields a [X]:1 social return on investment."},

  {"title":"CDBG Economic Development — Microenterprise Program","funder_name":"HUD","funder_type":"federal","program_name":"Community Development Block Grant","cfda_number":"14.218","section_key":"program_description","section_title":"Program Description","org_types":["nonprofit","municipal"],"program_types":["economic_development"],"tags":["CDBG","HUD","microenterprise","small_business"],"win_count":6,"use_count":15,"typical_word_limit":900,"content_md":"[Organization] will operate a microenterprise development program targeting low- and moderate-income entrepreneurs in [Target Area]. The program combines technical assistance, business coaching, and loan capital to help entrepreneurs launch and grow small businesses that create jobs in LMI census tracts.\n\n**Program Components:**\n\n*Business Development Training (12 weeks):* Participants complete a structured 12-week curriculum covering business planning, financial management, marketing, and legal/regulatory compliance. Classes meet twice weekly (evenings and Saturdays) to accommodate working adults.\n\n*One-on-One Coaching:* Each participant receives 10 hours of individualized coaching from a SCORE-certified mentor matched to their industry sector.\n\n*Loan Capital:* Graduating businesses are eligible for microloans of $2,500–$25,000 at below-market interest rates (current rate: [X]%) through our CDFI lending partner, [Partner Name].\n\n*Ongoing Support:* Program graduates access a peer network, quarterly workshops, and continuing coaching for 24 months post-graduation.\n\n**Target Outcomes (Year 1):** 40 participants enrolled; 32 complete training; 20 launch or expand a business; 15 access loan capital totaling $[X]; 35 jobs created or retained."},

  # ── SAMHSA ───────────────────────────────────────────────────────────────────
  {"title":"SAMHSA — Needs Statement: Substance Use in Rural Communities","funder_name":"SAMHSA","funder_type":"federal","program_name":"Substance Abuse Prevention and Treatment Block Grant","cfda_number":"93.959","section_key":"needs_statement","section_title":"Statement of Need","org_types":["nonprofit"],"program_types":["health","substance_use"],"tags":["SAMHSA","substance_use","rural","opioid"],"win_count":9,"use_count":27,"typical_word_limit":800,"content_md":"[County/Region] has experienced a [X]% increase in opioid overdose deaths over the past three years, from [X] deaths in [Year] to [X] deaths in [Year] (State Department of Health, [Year]). This rate — [X] per 100,000 residents — exceeds both state ([X]) and national ([X]) averages and qualifies [County] as a SAMHSA High-Intensity Drug Trafficking Area (HIDTA).\n\nAccess to treatment remains severely limited. There are [X] Medication-Assisted Treatment (MAT) providers serving a population of [X], a ratio of 1 provider per [X] residents compared to the national benchmark of 1 per [X]. The nearest residential treatment facility is [X] miles away — a prohibitive distance for low-income residents without transportation.\n\nHospital emergency department data reveals [X] substance use-related ED visits in [Year], a [X]% increase from [Year]. Of these patients, only [X]% received a referral to outpatient treatment, and fewer than [X]% initiated treatment within 30 days of discharge — demonstrating the critical gap in the continuum of care that this project will address."},

  {"title":"SAMHSA — Program Description: Co-Occurring Disorders Treatment","funder_name":"SAMHSA","funder_type":"federal","program_name":"Grants for the Benefit of Homeless Individuals","cfda_number":"93.914","section_key":"program_description","section_title":"Program Description","org_types":["nonprofit"],"program_types":["health","mental_health","substance_use","homelessness"],"tags":["SAMHSA","co-occurring","mental_health","homeless"],"win_count":7,"use_count":19,"typical_word_limit":1000,"content_md":"[Organization]'s proposed Integrated Recovery Program (IRP) will deliver evidence-based treatment for co-occurring substance use and mental health disorders to homeless and unstably housed individuals in [Service Area].\n\n**Theoretical Framework:** IRP uses the SAMHSA-endorsed Integrated Dual Diagnosis Treatment (IDDT) model, which treats substance use and mental health disorders simultaneously rather than sequentially, reducing the 'door-to-door' barrier that causes treatment dropout.\n\n**Services Delivered:**\n\n*Assertive Outreach:* Two full-time Outreach Specialists will conduct daily engagement at encampments, shelters, and emergency departments. Goal: 120 individuals engaged per year.\n\n*Comprehensive Assessment:* Licensed Clinical Social Workers administer AUDIT-C, PHQ-9, DAST-10, and ACE screening tools within 72 hours of engagement. Individual treatment plans developed within 5 business days.\n\n*Integrated Treatment:* MAT (buprenorphine, naltrexone) provided by an on-site prescribing physician (0.5 FTE). Individual and group therapy delivered by Licensed Professional Counselors using Cognitive Behavioral Therapy (CBT) and Motivational Enhancement Therapy (MET).\n\n*Housing Navigation:* Dedicated Housing Navigator coordinates with CoC continuum to secure permanent supportive housing placements. Target: 60% of enrolled clients housed within 6 months.\n\n*Peer Support:* Four Peer Recovery Specialists (Certified Recovery Coaches) with lived experience provide recovery coaching, medication adherence support, and crisis de-escalation."},

  {"title":"SAMHSA — Evaluation Plan: Substance Use Prevention","funder_name":"SAMHSA","funder_type":"federal","program_name":"Strategic Prevention Framework","cfda_number":"93.243","section_key":"evaluation","section_title":"Evaluation Plan","org_types":["nonprofit","municipal"],"program_types":["health","prevention"],"tags":["SAMHSA","prevention","evaluation","SPF"],"win_count":5,"use_count":14,"typical_word_limit":600,"content_md":"[Organization] will conduct a rigorous mixed-methods evaluation using both process and outcome measures aligned with SAMHSA's Strategic Prevention Framework.\n\n**Process Evaluation:** The Program Director will track implementation fidelity monthly using a structured checklist aligned with the [Program Model] fidelity standards. Indicators include: number of participants served (target: [X]); session attendance rates (target: [X]%); facilitator certification (100%); and curriculum delivery completeness (target: [X]%).\n\n**Outcome Evaluation:** An external evaluator, [Evaluator Name/Organization], will administer validated pre/post surveys using the [Validated Instrument, e.g., CRAFFT, ASSIST] at intake and 6-month follow-up. Primary outcomes: (1) reduction in past-30-day substance use; (2) improved protective factors (Resiliency Scales score); (3) increased refusal skills (RSES score). Secondary outcomes: school attendance, grade point average, and family communication quality.\n\n**Data Analysis:** Paired t-tests will assess pre/post differences. A minimum of [X]% follow-up rate is required for valid outcome analysis. Results will be presented at [X] community forums per year and submitted to SAMHSA's SPARS data system quarterly."},

  # ── USDA Rural Development ────────────────────────────────────────────────────
  {"title":"USDA Rural Development — Community Facilities Grant Need Statement","funder_name":"USDA Rural Development","funder_type":"federal","program_name":"Community Facilities Direct Loan and Grant Program","cfda_number":"10.766","section_key":"needs_statement","section_title":"Statement of Need","org_types":["nonprofit","municipal"],"program_types":["infrastructure","rural"],"tags":["USDA","rural","community_facilities","infrastructure"],"win_count":11,"use_count":23,"typical_word_limit":600,"content_md":"[Community Name] is a rural community of [X] residents in [County], [State], located [X] miles from the nearest metropolitan area. Per USDA rural eligibility criteria, [Community] qualifies as rural with a population below 20,000 and is not contiguous to an urban area.\n\nThe existing [Facility Type — e.g., community center, health clinic, fire station] was constructed in [Year] and has [X] square feet of usable space, serving a population that has grown [X]% over the past decade. The facility faces critical deficiencies: [describe specific deficiencies — structural, ADA compliance, capacity, safety]. A 2023 engineering assessment (attached as Exhibit A) estimates $[X] in deferred maintenance, with the building rated [X] on the Facility Condition Index.\n\nCommunity members currently travel [X] miles to access [Service Type] at alternative facilities. Lack of local access disproportionately affects elderly residents ([X]% of population aged 65+) and households without reliable transportation ([X]% per ACS data). A community needs survey conducted in [Month Year] received [X] responses, with [X]% rating the [facility type] as their top infrastructure priority."},

  {"title":"USDA Value-Added Producer Grant — Project Narrative","funder_name":"USDA Rural Development","funder_type":"federal","program_name":"Value-Added Producer Grant","cfda_number":"10.352","section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit"],"program_types":["economic_development","rural","agriculture"],"tags":["USDA","value-added","agriculture","rural_economy"],"win_count":4,"use_count":9,"typical_word_limit":800,"content_md":"[Applicant Name] proposes to use Value-Added Producer Grant funds to [describe value-added activity: e.g., 'expand our farm-to-institution direct marketing program to institutional buyers in [Region]'].\n\n**Value-Added Activity:** We will [specific activity] to transform [agricultural product] from [current form] to [value-added form]. This qualifies as value-added under the VAPG program definition because it [changes the physical state / produces a product using a specialty method / is sold directly by the producer].\n\n**Market Opportunity:** Direct-to-institution sales of [Product] in [Region] represent a $[X]M market growing at [X]% annually. Current institutional buyers — including [X] school districts, [X] hospitals, and [X] corporate cafeterias — pay a [X]% premium for locally sourced, [attribute] products. We have secured letters of intent from [X] buyers committing to purchase [X units/value] of product annually.\n\n**Working Capital Use:** Working capital funds ($[X]) will cover: raw agricultural inputs ($[X]); packaging and labeling ($[X]); marketing and direct sales staff ($[X]); and food safety certification ($[X]).\n\n**Producer Impact:** This project will increase gross revenues for [X] producer-owners by an average of $[X] per farm, creating [X] jobs and retaining [X] family farms in active agricultural production."},

  # ── DOJ ───────────────────────────────────────────────────────────────────────
  {"title":"DOJ VOCA — Victim Services Program Description","funder_name":"DOJ Office of Victims of Crime","funder_type":"federal","program_name":"Victims of Crime Act (VOCA) Victim Assistance","cfda_number":"16.575","section_key":"program_description","section_title":"Program Description","org_types":["nonprofit"],"program_types":["human_services","victims_services"],"tags":["DOJ","VOCA","victims_services","trauma-informed"],"win_count":10,"use_count":28,"typical_word_limit":900,"content_md":"[Organization]'s Comprehensive Victim Services Program provides trauma-informed crisis intervention, advocacy, and case management to survivors of domestic violence, sexual assault, stalking, and human trafficking in [Service Area].\n\n**Trauma-Informed Practice:** All services are delivered using a trauma-informed care framework consistent with SAMHSA's six principles: safety, trustworthiness, peer support, collaboration, empowerment, and cultural sensitivity. All direct service staff complete 40 hours of trauma-informed care training upon hire and 8 hours of continuing education annually.\n\n**Crisis Intervention:** Our 24/7 crisis hotline ([X] calls/year) is staffed by trained victim advocates. Walk-in crisis services are available during business hours; on-call advocates respond to hospital and law enforcement requests after hours (average response time: [X] minutes).\n\n**Advocacy Services:** Licensed Victim Advocates provide: (1) safety planning; (2) accompaniment to court, medical, and law enforcement appointments; (3) assistance with protective orders and crime victim compensation applications; (4) emergency financial assistance for relocation, childcare, and medical expenses.\n\n**Case Management:** Long-term case management (average [X] months) coordinates housing, legal, financial, and mental health services. Our outcomes database tracks 28 individual wellbeing domains using the [Validated Tool] at intake and 6-month intervals.\n\n**Cultural Competency:** [X]% of our advocates are bilingual. Services are available in [languages]. We partner with [X] culturally specific community organizations for referrals and co-advocacy."},

  {"title":"DOJ Byrne JAG — Community Violence Intervention Program","funder_name":"DOJ Bureau of Justice Assistance","funder_type":"federal","program_name":"Edward Byrne Memorial Justice Assistance Grant","cfda_number":"16.738","section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit","municipal"],"program_types":["public_safety","violence_prevention"],"tags":["DOJ","Byrne_JAG","violence_intervention","community_safety"],"win_count":6,"use_count":16,"typical_word_limit":1000,"content_md":"[City/Organization] proposes to implement a hospital-based violence intervention program (HVIP) targeting individuals aged 18–30 who present at [Hospital Name] emergency department with violent-injury-related diagnoses — the highest-risk moment for violence reinjury and retaliation.\n\n**Evidence Base:** Hospital-based violence intervention is a CDC-designated evidence-based strategy. A 2022 meta-analysis (Juillard et al.) found HVIP participants were 73% less likely to be reinjured and 69% less likely to be rearrested within 6 months compared to a matched control group.\n\n**Program Model:** Credible Messenger violence interrupters — individuals with lived experience of street violence who are trusted in the community — are stationed at the ED 24/7 during peak hours (Thu–Sun, 18:00–02:00). Within 24 hours of a violent-injury admission, interrupters:\n\n1. Conduct a bedside visit and build trust\n2. Complete a structured risk and needs assessment (LIVES tool)\n3. Develop an immediate safety plan for post-discharge\n4. Connect participants to intensive case management, job training, housing assistance, mental health services, and legal aid\n\n**Outcomes (Year 1):** 60 participants enrolled; [X]% 6-month retention; [X]% reduction in ED reinjury; [X]% employed or enrolled in education at 6 months."},

  # ── Private Foundations ───────────────────────────────────────────────────────
  {"title":"RWJF — Health Equity Program Narrative","funder_name":"Robert Wood Johnson Foundation","funder_type":"foundation","program_name":"Health Equity Initiatives","cfda_number":None,"section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit"],"program_types":["health","equity"],"tags":["RWJF","health_equity","social_determinants","foundation"],"win_count":5,"use_count":13,"typical_word_limit":1200,"content_md":"[Organization] seeks support from RWJF to [project description] — a community-driven initiative to address [specific health inequity] in [Community], where [population group] experiences [health outcome] at [X]× the rate of the general population.\n\n**Root Cause Analysis:** The health disparity documented above is not inevitable — it reflects structural inequities in [housing, food access, environmental exposure, healthcare access, economic opportunity]. Our theory of change: by [specific intervention addressing root cause], we will shift the conditions that drive the disparity, not just treat its symptoms.\n\n**Community Leadership:** This project is co-designed by a 12-member Community Advisory Board composed of [X]% residents with lived experience of the health inequity we are addressing. The Community Advisory Board has veto authority over program design decisions and will participate in data interpretation and dissemination.\n\n**Strategy:**\n[Strategy 1] — [description, timeline, person responsible]\n[Strategy 2] — [description, timeline, person responsible]\n[Strategy 3] — [description, timeline, person responsible]\n\n**Learning & Sharing:** We commit to documenting and sharing our learnings — including failures — through [publications, convenings, open-source tools]. RWJF-funded projects that share their models benefit the entire field."},

  {"title":"Annie E. Casey — Child & Family Services Need Statement","funder_name":"Annie E. Casey Foundation","funder_type":"foundation","program_name":"Child Welfare and Family Strengthening","cfda_number":None,"section_key":"needs_statement","section_title":"Statement of Need","org_types":["nonprofit"],"program_types":["youth","family_services","child_welfare"],"tags":["AECF","child_welfare","family_strengthening","foundation"],"win_count":4,"use_count":11,"typical_word_limit":700,"content_md":"In [County], [X] children are in out-of-home foster care — [X]% more than five years ago despite declining overall child population (State Child Welfare Data Book, [Year]). Among children ages 0–5, [X]% have experienced at least one confirmed child abuse or neglect report, a rate [X]× higher than the national average (AECF KIDS COUNT, [Year]).\n\nEntry into foster care has lasting consequences: children who experience placement instability are [X]× more likely to experience educational disruption, [X]× more likely to experience homelessness as adults, and [X]× more likely to have involvement with the juvenile justice system (AECF research synthesis, [Year]).\n\nThe primary driver of foster care entry in [County] is neglect (79% of cases) — which research consistently links to poverty, housing instability, and parental substance use, not parental malice. This means the majority of family separations are preventable with the right preventive services delivered at the right time.\n\n[Organization] has been providing family preservation services in [County] for [X] years. Our waitlist currently stands at [X] families — families that are at risk of separation while waiting for services that could keep them together."},

  {"title":"MacArthur Foundation — Criminal Justice Reform","funder_name":"MacArthur Foundation","funder_type":"foundation","program_name":"Safety and Justice Challenge","cfda_number":None,"section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit","municipal"],"program_types":["criminal_justice","public_safety"],"tags":["MacArthur","criminal_justice","jail_reform","foundation"],"win_count":3,"use_count":8,"typical_word_limit":1000,"content_md":"[County/City] proposes [Project Name] — a cross-system initiative to reduce pretrial detention by [X]% over three years through bail reform, pretrial services expansion, and community supervision alternatives that address racial disparities in the [County] criminal justice system.\n\n**Current State:** [County] Jail holds an average daily population of [X], of whom [X]% are pretrial detainees — individuals who have not been convicted of a crime. [X]% of pretrial detainees are held solely because they cannot afford bail of $1,000 or less. The racial disparity is stark: Black individuals are [X]× more likely to be detained pretrial than white individuals charged with comparable offenses.\n\n**Reform Strategy:**\n\n1. *Pretrial Assessment:* Implement the Arnold Foundation's Public Safety Assessment (PSA) for all arrests, replacing money bail with risk-based release decisions.\n\n2. *Community Supervision:* Expand pretrial supervision slots from [X] to [X], with a Supervision Navigator model that connects defendants to housing, employment, and treatment services — addressing the root conditions that drive failure to appear.\n\n3. *Community-Based Organizations:* Contract with [X] community organizations to provide court reminders, transportation to hearings, and wraparound support for high-risk defendants.\n\n4. *Data Transparency:* Publish monthly public dashboards on pretrial detention rates, racial disparities, and failure-to-appear rates."},

  {"title":"Kresge Foundation — Arts & Culture Capital Request","funder_name":"Kresge Foundation","funder_type":"foundation","program_name":"Arts & Culture Program","cfda_number":None,"section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit"],"program_types":["arts","culture","capital"],"tags":["Kresge","arts_culture","capital_project","placemaking"],"win_count":3,"use_count":7,"typical_word_limit":900,"content_md":"[Organization] seeks a Kresge Arts & Culture grant to support Phase 2 of [Project Name] — the renovation of [Facility Description] into a permanently affordable creative hub for artists of color in [Neighborhood], [City].\n\n**The Displacement Crisis:** [Neighborhood] has lost [X]% of its affordable artist studios and live/work spaces over the past decade as commercial rents have increased [X]% (Urban Land Institute, [Year]). Artists — disproportionately artists of color — face displacement from the neighborhoods they have anchored and the communities they serve.\n\n**The Project:** [Organization] has secured ownership of [Property Address], a [X] sq ft [building type] at the heart of [Neighborhood]'s cultural district. Phase 1 (completed [Year]) stabilized the structure and installed mechanical systems. Phase 2 will complete interior build-out of [X] artist studios ([X] affordable at 60% AMI, [X] at 30% AMI), a 200-seat performance/event space, and shared equipment and gallery areas.\n\n**Permanent Affordability:** [Organization] holds the property in a Community Land Trust structure that permanently restricts commercial rents and requires future tenants to be working artists. This model has been used successfully by [Peer Organization] in [City] to protect [X] artist studios over [X] years.\n\n**Community Ownership:** [X]% of our board members are artists who are current or former tenants. Artist governance of the facility is written into our CLT ground lease."},

  # ── NEH ───────────────────────────────────────────────────────────────────────
  {"title":"NEH — Humanities Initiative Project Description","funder_name":"National Endowment for the Humanities","funder_type":"federal","program_name":"Humanities Collections and Reference Resources","cfda_number":"45.149","section_key":"project_description","section_title":"Project Description","org_types":["nonprofit"],"program_types":["arts","education","preservation"],"tags":["NEH","humanities","preservation","archive"],"win_count":6,"use_count":17,"typical_word_limit":1500,"content_md":"[Organization] proposes to [digitize/catalog/publish/preserve] the [Collection Name], a collection of [X] items documenting [subject, period, community] held at [Repository]. This project will make [X] previously inaccessible primary sources available to researchers, educators, and the public for the first time.\n\n**Significance:** The [Collection Name] is the most comprehensive archive of [subject/community/period] in [Region/Nation]. It contains [types of materials: photographs, correspondence, manuscript volumes, ephemera] created between [years] that document [specific humanities significance: a critical period of social movement history / an underrepresented community's cultural life / an important literary figure's creative process].\n\nCurrent scholarship on [subject] relies heavily on [existing sources], which [limitation]. The [Collection Name] fills this gap by providing [specific types of new evidence/perspectives]. [Scholar X] has noted that 'access to the [Collection] would fundamentally change our understanding of [specific claim]' (personal correspondence, [Date]).\n\n**Methodology:** Working with a project team of [X] archivists, [X] metadata specialists, and [X] subject scholars, we will: (1) conduct physical preservation assessment and remediation for fragile items; (2) digitize [X] items at archival resolution (600 dpi minimum); (3) create MARC/EAD metadata records meeting national standards; (4) publish all materials openly via [Platform: HathiTrust/Internet Archive/institutional repository] under a Creative Commons license.\n\n**Public Access:** All digitized materials and finding aids will be freely accessible at [URL]. We will develop a curated online exhibit, a teacher's guide for secondary educators, and a community engagement series in partnership with [Community Organizations]."},

  {"title":"NEH — Preservation and Access: Work Plan","funder_name":"National Endowment for the Humanities","funder_type":"federal","program_name":"Preservation and Access","cfda_number":"45.149","section_key":"work_plan","section_title":"Work Plan","org_types":["nonprofit"],"program_types":["preservation","education"],"tags":["NEH","preservation","work_plan","archive","digitization"],"win_count":5,"use_count":14,"typical_word_limit":800,"content_md":"**Project Timeline: [Start Month, Year] — [End Month, Year]**\n\n**Months 1–3: Assessment and Planning**\n- Project Archivist conducts condition assessment of all [X] items; identifies [X] priority items for conservation treatment\n- Conservation Consultant completes written condition report and treatment recommendations\n- Project team meets with Advisory Board to review priorities and confirm metadata schema\n- Digitization workflow tested and equipment calibrated\n\n**Months 4–9: Digitization and Description**\n- Project Archivist and Assistant Archivist digitize [X] items/month (pace: [X] items/day)\n- Metadata Specialist creates EAD finding aid and MARC records; uploads to [system] monthly\n- Quality control review: [X]% sampling by Project Director\n- Monthly progress reports submitted to NEH project officer\n\n**Months 10–15: Processing and Public Access**\n- All digitized files uploaded to [Platform]\n- Teacher's guide drafted and reviewed by [X] classroom teachers\n- Community engagement events: [X] public programs at [venues]\n- Advisory Board reviews final products\n\n**Months 16–18: Dissemination and Closeout**\n- Online exhibit launched; press release distributed\n- Final report submitted to NEH\n- Preservation plan for physical collection completed and filed with [Repository]\n- All project files archived per NEH requirements"},

  # ── EPA / Environment ─────────────────────────────────────────────────────────
  {"title":"EPA Environmental Justice — Community Needs Assessment","funder_name":"EPA","funder_type":"federal","program_name":"Environmental Justice Collaborative Problem-Solving","cfda_number":"66.309","section_key":"needs_statement","section_title":"Community Needs and Environmental Justice Concerns","org_types":["nonprofit","municipal"],"program_types":["environment","equity","health"],"tags":["EPA","environmental_justice","EJ","pollution","community"],"win_count":7,"use_count":19,"typical_word_limit":700,"content_md":"[Community Name] is a [demographic description] community in [City/County] that bears a disproportionate environmental burden relative to the surrounding region. According to EPA's EJScreen tool, [Community] ranks at the [X]th percentile nationally for [environmental indicator: air toxics, proximity to RMP facilities, wastewater discharge proximity, etc.] — placing it among the most environmentally overburdened communities in [State].\n\n**Environmental Hazards:**\n- Air quality: PM2.5 levels in [Community] average [X] μg/m³, [X]× the EPA annual standard\n- Proximity to industry: [X] industrial facilities within [X] miles, including [X] major sources of [pollutants]\n- [Additional hazard type]: [data and source]\n\n**Health Impacts:** The cumulative environmental burden correlates with documented health disparities. Childhood asthma rates in [Zip Code] are [X]%, versus [X]% countywide (Health Department, [Year]). Emergency department visits for respiratory illness are [X]× higher than county average. Cancer incidence for [type] is [X]× the state average (State Cancer Registry, [Year]).\n\n**Community Capacity:** Despite these burdens, [Community] has limited capacity to address them: [X]% of households are below the federal poverty level; [X]% are renters with limited political power; and there is no full-time environmental health advocate serving the community. This project will build that capacity."},

  # ── NSF / Education ───────────────────────────────────────────────────────────
  {"title":"NSF — Broader Impacts Statement","funder_name":"National Science Foundation","funder_type":"federal","program_name":"Research and Related Activities","cfda_number":"47.070","section_key":"broader_impacts","section_title":"Broader Impacts","org_types":["nonprofit"],"program_types":["education","research","STEM"],"tags":["NSF","broader_impacts","STEM_education","research"],"win_count":8,"use_count":21,"typical_word_limit":500,"content_md":"This project advances NSF's mission by generating fundamental knowledge in [field] while simultaneously expanding access to STEM research experiences for underrepresented groups.\n\n**Scientific Impact:** The findings from this research will [specific advance: resolve a longstanding question / provide a new computational framework / generate an open dataset]. We will publish results in high-impact peer-reviewed journals and make all data, code, and materials freely available under open-access licenses.\n\n**Workforce Development:** The project will support [X] graduate students and [X] undergraduate researchers, with intentional recruitment from underrepresented groups through partnerships with [X] HBCUs and [X] community colleges. Graduate students will receive professional development in science communication, data management, and grant writing.\n\n**Public Engagement:** The PI will develop a [curriculum unit/public exhibit/podcast series] in partnership with [K-12 school/museum/public library] to translate research findings for non-specialist audiences. Target reach: [X] students or community members annually.\n\n**Partnerships:** Industry partner [Company] will provide [resources/data/infrastructure] and create internship pathways for [X] project alumni annually."},

  # ── Community Foundation ──────────────────────────────────────────────────────
  {"title":"Community Foundation — Organizational Capacity Statement","funder_name":"Community Foundation","funder_type":"community_foundation","program_name":"Capacity Building Grants","cfda_number":None,"section_key":"organizational_capacity","section_title":"Organizational Capacity","org_types":["nonprofit"],"program_types":["capacity_building"],"tags":["community_foundation","capacity","governance","nonprofit_management"],"win_count":9,"use_count":25,"typical_word_limit":600,"content_md":"[Organization] has demonstrated consistent organizational strength through [X] years of operations, a track record of fiscal accountability, and a governance structure designed for long-term sustainability.\n\n**Financial Health:** Our FY[Year] audit (attached) reflects total revenues of $[X], a [X]% operating surplus, and [X] months of operating reserves — exceeding the recommended 3-month benchmark. We have maintained clean audits for [X] consecutive years. Debt-to-asset ratio of [X]% is well within conservative nonprofit management guidelines.\n\n**Leadership:** Our [X]-member Board of Directors includes expertise in [finance/law/program area/fundraising/lived experience]. The Board meets [X times/year], maintains active Finance and Program Committees, and conducted a full governance assessment in [Year] using BoardSource standards.\n\n**Staff Capacity:** [X] FTE staff have an average of [X] years of experience in [program area]. Key program staff turnover over the past 3 years: [X]% — well below sector average of [X]%.\n\n**Program Track Record:** In FY[Year], we served [X] clients/participants, achieving [key outcome] for [X]% of participants — compared to our target of [X]% and sector benchmark of [X]%. We have successfully managed [X] grants from [funder types] over the past [X] years with no audit findings."},

  {"title":"Community Foundation — Sustainability Plan","funder_name":"Community Foundation","funder_type":"community_foundation","program_name":"Operating Support","cfda_number":None,"section_key":"sustainability","section_title":"Sustainability Plan","org_types":["nonprofit"],"program_types":["capacity_building","sustainability"],"tags":["community_foundation","sustainability","fund_development","foundation"],"win_count":7,"use_count":18,"typical_word_limit":500,"content_md":"[Organization]'s long-term financial sustainability rests on a diversified revenue model that reduces dependence on any single funder.\n\n**Current Revenue Mix (FY[Year]):**\n- Government grants and contracts: [X]% ($[X])\n- Foundation grants: [X]% ($[X])\n- Individual donors: [X]% ($[X])\n- Earned revenue/fees: [X]% ($[X])\n- Other: [X]% ($[X])\n\n**Three-Year Development Plan:**\nOver the grant period, we will pursue three sustainability strategies:\n\n1. *Individual donor cultivation:* Launch a mid-level donor program targeting [X] donors giving $1,000–$10,000. Current base: [X] donors; target by Year 3: [X] donors.\n\n2. *Earned revenue:* Develop [fee-for-service model/training program/social enterprise] generating $[X] annually by Year 3, reducing grant dependency by [X]%.\n\n3. *Endowment:* Launch a $[X] endowment campaign with [X] lead donors committed. A $[X] endowment would generate $[X] in annual investment income, permanently funding [specific program component].\n\n**After the grant period:** This specific project will be sustained through [specific plan: inclusion in government contract renewal / fee-for-service conversion / folding into ongoing programming]."},

  # ── AmeriCorps ────────────────────────────────────────────────────────────────
  {"title":"AmeriCorps VISTA — Project Description","funder_name":"AmeriCorps","funder_type":"federal","program_name":"Volunteers in Service to America (VISTA)","cfda_number":"94.013","section_key":"project_description","section_title":"Project Description","org_types":["nonprofit","municipal"],"program_types":["capacity_building","anti-poverty"],"tags":["AmeriCorps","VISTA","capacity_building","anti-poverty"],"win_count":8,"use_count":22,"typical_word_limit":750,"content_md":"[Organization] will host [X] AmeriCorps VISTA members to build organizational capacity to address [poverty/economic opportunity/food insecurity/other VISTA focus area] in [Service Area].\n\n**VISTA Activities:** Each VISTA member will serve in a capacity-building role — not providing direct services — to develop systems, resources, and infrastructure that will outlast their term of service.\n\n*VISTA 1 — Development & Grants:* Will research and write [X] grant applications, develop a first-time donor acquisition strategy, and create a development tracking system (projected outcome: $[X] in new grant revenue over the VISTA term).\n\n*VISTA 2 — Volunteer Engagement:* Will recruit, train, and manage a cohort of [X] community volunteers, creating a volunteer management handbook, onboarding curriculum, and recognition program (projected outcome: [X] volunteer hours/year, valued at $[X]).\n\n*VISTA 3 — Technology & Data:* Will migrate program data to a Salesforce NPSP implementation, create outcome dashboards, and train staff on data-informed decision-making (projected outcome: [X] staff hours/year saved; real-time program performance visibility).\n\n**Supervision and Support:** VISTAs will be supervised by [Name/Title], who has [X] years of VISTA supervision experience. VISTAs will receive [X] hours/week of structured supervision, participate in monthly cohort learning calls, and have access to professional development funding of $[X]/member."},

  # ── HHS / ACF ─────────────────────────────────────────────────────────────────
  {"title":"HHS ACF — Head Start Program Description","funder_name":"HHS Administration for Children and Families","funder_type":"federal","program_name":"Head Start","cfda_number":"93.600","section_key":"program_description","section_title":"Program Description","org_types":["nonprofit","municipal"],"program_types":["early_childhood","education"],"tags":["HHS","ACF","Head_Start","early_childhood","preschool"],"win_count":9,"use_count":26,"typical_word_limit":1000,"content_md":"[Organization]'s Head Start/Early Head Start program provides comprehensive early childhood education, health, nutrition, and family support services to [X] children ages birth through 5 and their families in [Service Area].\n\n**Education and Child Development:** Our program implements the [Curriculum Name — e.g., Creative Curriculum, HighScope] fidelity model, a research-based approach aligned with Head Start Early Learning Outcomes Framework (ELOF) domains. All classrooms meet Head Start Program Performance Standards ratios (1:8 for preschool; 1:4 for infants/toddlers). All lead teachers hold minimum AA degrees in Early Childhood Education; [X]% hold BA or higher.\n\n**Health and Nutrition:** We partner with [Health Provider] to coordinate comprehensive health screenings (vision, hearing, dental, developmental) for 100% of enrolled children within 45 days of entry. [X]% of children are enrolled in Medicaid/CHIP within 90 days. We serve USDA-reimbursed meals meeting nutritional standards.\n\n**Family Engagement:** Our Parent, Family, and Community Engagement (PFCE) framework is built on the Head Start Parent, Family, and Community Engagement Framework. Each family receives an annual Family Partnership Agreement; [X] home visits per year per family; and access to [X] community resource navigators.\n\n**Disabilities Services:** [X]% of enrollment is reserved for children with disabilities per HSPPS 1305.7. We employ [X] FTE disabilities services coordinator and maintain IEP compliance for 100% of identified children."},

  {"title":"HHS — Budget Justification: Personnel Section","funder_name":"HHS","funder_type":"federal","program_name":"General HHS Grant","cfda_number":None,"section_key":"budget_justification","section_title":"Budget Justification — Personnel","org_types":["nonprofit","municipal"],"program_types":["general"],"tags":["HHS","budget_justification","personnel","fringe"],"win_count":14,"use_count":42,"typical_word_limit":400,"content_md":"**Personnel: $[X]**\n\n*Program Director ([Name or TBD]):* $[X]/year × [X]% FTE = $[X]. The Program Director will provide overall program leadership, manage program staff, oversee implementation fidelity, coordinate with [Funder] program officer, and ensure compliance with grant requirements. [Name] has [X] years of experience managing [program type] grants and holds [relevant credential].\n\n*Case Manager ([X] positions):* $[X]/year × 100% FTE × [X] FTEs = $[X]. Case Managers will carry caseloads of [X] participants each, providing [service description]. Salaries reflect the [City] market rate for [position type] as verified by [salary survey].\n\n*Administrative Coordinator ([Name or TBD]):* $[X]/year × [X]% FTE = $[X]. The Administrative Coordinator will manage program data entry, scheduling, participant communications, and financial reporting. This position is [X]% charged to this grant and [X]% funded by other sources.\n\n**Fringe Benefits: $[X] ([X]% of $[X] in direct salaries)**\n\n[Organization]'s fringe benefit rate of [X]% covers: FICA (7.65%), health insurance ([X]%), dental/vision ([X]%), retirement ([X]%), and workers compensation/unemployment insurance ([X]%). This rate has been reviewed by [cognizant agency or auditor] and is applied consistently across all funding sources."},

  # ── State Government ──────────────────────────────────────────────────────────
  {"title":"State CSBG — Community Services Block Grant Program Plan","funder_name":"State CSBG Office","funder_type":"state","program_name":"Community Services Block Grant","cfda_number":"93.569","section_key":"program_description","section_title":"Community Action Program Plan","org_types":["nonprofit"],"program_types":["human_services","anti-poverty"],"tags":["CSBG","state","community_action","anti-poverty","CAP"],"win_count":11,"use_count":31,"typical_word_limit":800,"content_md":"[Organization] is the designated Community Action Agency for [County/Multi-County Region], serving low-income residents defined at or below 200% of the Federal Poverty Level. As an eligible entity under the Community Services Block Grant, we provide a comprehensive network of services addressing the Organizational Standards and ROMA Next Generation outcomes.\n\n**Priority Families:** Community needs assessment data identifies the following priority family types: (1) working poor families with incomes 100–150% FPL earning too much for benefits but unable to meet basic needs; (2) families with young children (ages 0–5) at risk of adverse childhood experiences; (3) single-parent households headed by women of color, who represent [X]% of our poverty population but [X]% of families we serve.\n\n**Service Array:** Aligned with CSBG outcomes in Employment, Education, Income and Assets, Housing, Health, and Emergency situations, we provide:\n- *Employment:* [X] workforce development slots; job placement services; EITC outreach\n- *Education:* [X] Head Start slots; adult literacy partnerships; school readiness services\n- *Income & Assets:* financial coaching; VITA tax preparation; benefits enrollment ([X] families enrolled in public benefits/year)\n- *Housing:* emergency rental assistance; homebuyer education; weatherization coordination\n- *Health:* health coverage enrollment; community health worker services\n- *Emergency:* utility assistance; food pantry coordination; emergency transportation"},

  {"title":"State Housing Trust Fund — Affordable Housing Development","funder_name":"State Housing Finance Agency","funder_type":"state","program_name":"State Housing Trust Fund","cfda_number":None,"section_key":"project_narrative","section_title":"Project Narrative","org_types":["nonprofit","municipal"],"program_types":["housing","affordable_housing"],"tags":["housing_trust_fund","state","affordable_housing","LIHTC","development"],"win_count":7,"use_count":18,"typical_word_limit":1000,"content_md":"[Organization] requests State Housing Trust Fund financing to support [Project Name] — the development of [X] units of affordable housing at [Address/Location] in [City], [County].\n\n**Project Overview:** [Project Name] will develop [X] units of [rental/homeownership] housing serving households earning [X–X]% of Area Median Income. The project is located in [neighborhood description] with access to [transit, employment centers, schools, services].\n\n**Affordability Structure:**\n- [X] units at [X]% AMI (rent: $[X]/month for [bedroom type])\n- [X] units at [X]% AMI (rent: $[X]/month for [bedroom type])\n- [X] units at market rate (rent: $[X]/month) — used to cross-subsidize affordable units\n\n**Financing Sources:**\n| Source | Amount | Status |\n|--------|--------|--------|\n| State Housing Trust Fund (requested) | $[X] | Pending |\n| Federal LIHTC equity (4%) | $[X] | Committed |\n| HOME funds | $[X] | Committed |\n| Permanent first mortgage | $[X] | Term sheet received |\n| Deferred developer fee | $[X] | Committed |\n| **Total** | **$[X]** | |\n\n**Development Team:** [Organization] has developed [X] units of affordable housing over [X] years with a [X]% on-time completion rate. [General Contractor] has completed [X] affordable housing projects in [State]. [Architect] is [certifications/experience]."},

  # ── Win Score / Cross-Funder ──────────────────────────────────────────────────
  {"title":"General — Organizational History and Mission Alignment","funder_name":"General","funder_type":"general","program_name":"General Grants","cfda_number":None,"section_key":"organizational_capacity","section_title":"Organizational History & Mission Alignment","org_types":["nonprofit"],"program_types":["general"],"tags":["general","org_history","mission","capacity"],"win_count":16,"use_count":48,"typical_word_limit":500,"content_md":"[Organization] was founded in [Year] by [founding story: community members / practitioners / survivors / researchers] who recognized [founding insight about the problem]. For [X] years, we have been [mission statement in action] in [Geographic Area].\n\nOur mission — [mission statement] — directly aligns with [Funder]'s stated priorities of [funder priorities]. Specifically, [Funder]'s focus on [specific priority] maps directly to our [specific program/approach/population].\n\n[Organization] operates [X] programs serving [X] clients/participants annually with a budget of $[X]. We are [IRS status; accreditations; memberships] and have received [notable recognitions, awards, media coverage] for our work.\n\nOver [X] years, we have: (1) served [X] total clients/participants; (2) achieved [key outcome] for [X]% of participants; (3) developed [innovation/model/tool] that has been replicated by [X] organizations in [X] states; and (4) maintained a [X]% client satisfaction rating on annual surveys."},

  {"title":"General — Goals, Objectives, and Measurable Outcomes","funder_name":"General","funder_type":"general","program_name":"General Grants","cfda_number":None,"section_key":"goals_objectives","section_title":"Goals, Objectives, and Measurable Outcomes","org_types":["nonprofit","municipal"],"program_types":["general"],"tags":["general","goals","SMART_objectives","logic_model","outcomes"],"win_count":18,"use_count":55,"typical_word_limit":600,"content_md":"**Goal 1:** [Broad goal statement aligned with funder priority]\n\n*Objective 1.1:* By [Month, Year], [X] participants will [specific measurable action] as measured by [measurement tool/method], with a target of [X]% success rate.\n\n*Objective 1.2:* By [Month, Year], [X] participants will demonstrate [measurable improvement] in [outcome area] as measured by pre/post [assessment tool], with a minimum [X]% improvement threshold.\n\n**Goal 2:** [Second broad goal statement]\n\n*Objective 2.1:* By [Month, Year], [Organization] will have [capacity/system/partnership] in place as evidenced by [documentation: signed MOU / completed staff training / operational system].\n\n*Objective 2.2:* By [Month, Year], [X]% of program graduates will report [outcome] at [X]-month follow-up survey.\n\n**Logic Model Summary:**\n- *Inputs:* $[X] grant funding; [X] FTE staff; [X] partner organizations; [facilities/technology]\n- *Activities:* [List key program activities]\n- *Outputs:* [X] participants enrolled; [X] service hours delivered; [X] products created\n- *Short-term outcomes:* [Changes in knowledge, skills, attitudes]\n- *Long-term outcomes:* [Changes in behavior, conditions, systems]\n- *Impact:* [Community-level change aligned with funder's theory of change]"},

  {"title":"General — Evaluation Framework for Any Grant Type","funder_name":"General","funder_type":"general","program_name":"General Grants","cfda_number":None,"section_key":"evaluation","section_title":"Evaluation Plan","org_types":["nonprofit","municipal"],"program_types":["general"],"tags":["general","evaluation","outcomes_measurement","data_collection"],"win_count":15,"use_count":44,"typical_word_limit":500,"content_md":"**Evaluation Design:** [Organization] will conduct a continuous quality improvement evaluation combining formative and summative components to assess program implementation and outcomes.\n\n**Data Collection Methods:**\n| Data Type | Instrument | Collection Frequency | Responsible Party |\n|-----------|------------|---------------------|------------------|\n| Participant enrollment | Intake form | At enrollment | Case Manager |\n| Service utilization | Activity log | Ongoing | Program Staff |\n| Short-term outcomes | Pre/post survey | At intake and [X] months | Program Director |\n| Long-term outcomes | Follow-up survey | At [X] and [X] months | Data Coordinator |\n| Participant satisfaction | Satisfaction survey | At exit | Case Manager |\n\n**Analysis:** Quantitative data will be analyzed using descriptive statistics and paired t-tests for pre/post comparisons. Qualitative data (case notes, focus groups) will be analyzed using content analysis to identify themes. Analysis will be conducted [quarterly/semi-annually] by [staff/external evaluator].\n\n**Learning and Adaptation:** Results will be reviewed quarterly by program leadership and the [Board Committee]. Findings will be used to adapt program delivery. We commit to transparent reporting: annual program reports will be publicly available on our website."},

  {"title":"General — Letters of Support Template Guidance","funder_name":"General","funder_type":"general","program_name":"General Grants","cfda_number":None,"section_key":"attachments","section_title":"Letters of Support / Partnership Letters","org_types":["nonprofit","municipal"],"program_types":["general"],"tags":["general","letters_of_support","partnerships","MOU"],"win_count":13,"use_count":39,"typical_word_limit":300,"content_md":"**Effective letters of support include:**\n\n1. *Who is writing:* Name, title, organization, and their relationship to the applicant\n2. *What they know:* Specific evidence they have observed the applicant's work and competence\n3. *What they commit to:* Specific, concrete commitments (not just general support) — referrals, data sharing, co-location, in-kind resources, collaborative activities\n4. *Why this matters:* Their stake in the problem and why this project is the right solution\n\n**Red flags reviewers notice:**\n- Generic letters with no specific project reference\n- Letters that only say 'we support this organization' with no specific commitments\n- Letters from organizations with no evident connection to the target population\n- Letters that are clearly templates with fill-in-the-blank names\n\n**Sample language for commitment paragraph:**\n'[Partner Organization] commits to: (1) referring [X] eligible clients/month to [Program]; (2) providing co-located space at [Address] for [X] days/week at no cost; (3) sharing de-identified outcome data for program evaluation purposes; and (4) participating in [X] joint training events per year.'"},

  # ── CDBG-DR / Disaster Recovery ───────────────────────────────────────────────
  {"title":"CDBG-DR — Disaster Recovery Needs Assessment","funder_name":"HUD","funder_type":"federal","program_name":"CDBG Disaster Recovery","cfda_number":"14.269","section_key":"needs_statement","section_title":"Unmet Disaster Recovery Needs","org_types":["nonprofit","municipal"],"program_types":["housing","disaster_recovery"],"tags":["CDBG-DR","HUD","disaster_recovery","housing","unmet_needs"],"win_count":6,"use_count":14,"typical_word_limit":800,"content_md":"[Disaster Name/Event] struck [Area] on [Date], causing $[X] in total damages across [County/Region]. [Organization's service area] sustained particularly severe impacts: [X] residential structures damaged or destroyed; [X] households displaced; [X] businesses forced to close.\n\nFederal disaster assistance has addressed a portion of recovery needs, but significant unmet needs persist:\n\n**Housing Unmet Needs:** FEMA Individual Assistance awards averaged $[X] per household, far below the estimated $[X] average repair cost for substantially damaged homes. HUD's Unmet Needs Analysis estimates [X] households in [Area] have unmet housing recovery needs totaling $[X]M.\n\n**Low-Income Household Concentration:** [X]% of substantially damaged owner-occupied homes are owned by households with incomes at or below 80% AMI — households least able to self-fund recovery. [X]% are elderly homeowners living alone.\n\n**LMI Area Targeting:** [X]% of the proposed target area qualifies as an LMI area per HUD census data, satisfying CDBG-DR's national objective requirement. The [X] target census tracts contain [X]% of the County's unmet housing needs despite comprising [X]% of its geographic area.\n\n**Program Design Response:** Our Homeowner Rehabilitation and Reconstruction program will serve [X] households in the first program year, prioritizing elderly and disabled homeowners in LMI census tracts with unmet needs not covered by FEMA or SBA."},

  # ── Title I / Education ───────────────────────────────────────────────────────
  {"title":"Title I — School Improvement Grant Program Narrative","funder_name":"US Department of Education","funder_type":"federal","program_name":"Title I, Part A — Improving Basic Programs","cfda_number":"84.010","section_key":"program_description","section_title":"Program Description and Theory of Change","org_types":["nonprofit","municipal"],"program_types":["education","youth","K-12"],"tags":["Title_I","education","school_improvement","low-income_students","ESSA"],"win_count":7,"use_count":21,"typical_word_limit":900,"content_md":"[School/District/Organization] proposes [Program Name] — an evidence-based literacy intervention targeting [X] students in grades [X–X] at [School Name(s)] who are reading below grade level.\n\n**Evidence Base:** The proposed intervention, [Program Name], is listed in the [What Works Clearinghouse / CASEL Guide / other repository] with evidence ratings of [Strong/Moderate/Promising] evidence for improving [reading fluency / comprehension / writing skills]. Effect sizes in studies most similar to our context range from d=[X] to d=[X].\n\n**Theory of Change:** If we provide [X] minutes of additional structured literacy instruction per day using [evidence-based method], to students reading at least [X] grade levels below benchmark, then students will gain an average of [X] months of additional reading growth over a [X]-month intervention, closing the achievement gap by [X]%.\n\n**Implementation:**\n- *Who is served:* [X] students per year, identified by [DIBELS/Fountas & Pinnell/other screening] at or below the [X]th percentile at start of year\n- *Who delivers:* [X] interventionists with [X] hours of program-specific training\n- *How often:* [X] minutes/day, [X] days/week, in groups of [X–X] students\n- *How long:* [X]-week intervention cycles; students exit when benchmark is met\n\n**Outcomes Measured:** [Assessment name] administered at [X]-week intervals. Primary outcome: [X]% of participating students will meet or exceed grade-level benchmark by spring assessment."},

  # ── Affordable Care Act / Federally Qualified Health Centers ──────────────────
  {"title":"HRSA FQHC — New Access Point Needs Assessment","funder_name":"HRSA","funder_type":"federal","program_name":"Health Center Program — New Access Point","cfda_number":"93.224","section_key":"needs_assessment","section_title":"Need for Assistance","org_types":["nonprofit"],"program_types":["health","primary_care","FQHC"],"tags":["HRSA","FQHC","health_center","primary_care","underserved"],"win_count":5,"use_count":13,"typical_word_limit":800,"content_md":"The proposed service area for [Organization]'s New Access Point encompasses [X] zip codes in [County], with a total population of [X] residents. The area meets HRSA criteria as a Health Professional Shortage Area (HPSA) with a score of [X] (threshold: 0), an Index of Medical Underservice (IMU) score of [X] (threshold: 62.0), and [X] existing primary care providers serving a population-to-provider ratio of [X]:1.\n\n**Target Population:** [Organization]'s proposed patient population includes:\n- [X]% Medicaid/CHIP\n- [X]% uninsured\n- [X]% at or below 200% FPL\n- [X]% racial/ethnic minority (compared to [X]% in broader county)\n- Significant populations of [agricultural workers/seasonal workers/homeless individuals/public housing residents] — qualifying for FQHC 'special populations' designation\n\n**Current Access Barriers:**\n- Nearest existing FQHC: [X] miles, with public transit requiring [X]+ transfers and [X]+ hours\n- Nearest safety-net provider accepting new Medicaid patients: [X] mile wait list of [X] patients\n- Emergency department use for primary care-treatable conditions: [X]% of ED visits in [Zip Code] (far above [X]% benchmark)\n\n**Community Engagement:** A community health needs assessment conducted in [Month Year] with [X] community members confirmed primary care access as the top health priority for [X]% of respondents."},
]

headers = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=minimal",
}

# Build insert records (no embedding for now — use NULL)
records = []
for t in TEMPLATES:
    records.append({
        "title": t["title"],
        "funder_name": t.get("funder_name"),
        "funder_type": t.get("funder_type"),
        "program_name": t.get("program_name"),
        "cfda_number": t.get("cfda_number"),
        "section_key": t["section_key"],
        "section_title": t["section_title"],
        "content_md": t["content_md"],
        "word_count": len(t["content_md"].split()),
        "typical_word_limit": t.get("typical_word_limit", 600),
        "org_types": t.get("org_types", []),
        "program_types": t.get("program_types", []),
        "tags": t.get("tags", []),
        "win_count": t.get("win_count", 0),
        "use_count": t.get("use_count", 0),
        "is_public": True,
    })

# Insert in batches of 10
batch_size = 10
inserted = 0
for i in range(0, len(records), batch_size):
    batch = records[i:i+batch_size]
    data = json.dumps(batch).encode()
    req = urllib.request.Request(
        f"{SUPABASE_URL}/rest/v1/templates",
        data=data,
        headers=headers,
        method="POST",
    )
    try:
        with urllib.request.urlopen(req) as resp:
            inserted += len(batch)
            print(f"Inserted batch {i//batch_size + 1}: {len(batch)} records (total: {inserted})")
    except urllib.error.HTTPError as e:
        print(f"Error batch {i//batch_size + 1}: {e.code} {e.read().decode()}")

print(f"\nDone. {inserted} templates inserted.")
